### ISSUE TITLE
Syntax error on error messages of make_taxonomy_table.py, making it unable to run

### ISSUE THREAD

**Issue by benjaminjtc** [KwanLab/Autometa#109]
## Current Behavior
When running the make_taxonomy_table.py file, the following messages pops: 

>   File "/home/usr/bin/Autometa/pipeline/make_taxonomy_table.py", line 233
>     print **"**{} file already exists!".format(output_path)
>            ^
> SyntaxError: invalid syntax

and line 273 also have the same error msg and behaviour, stopping the program from running at all

### Steps to Reproduce
Command ran:
make_taxonomy_table.py --assembly ~/bin/Autometa/test_data/scaffolds.fasta --processors 16 --length_cutoff 3000

## Expected Behavior
the program should've continued even if there are any file already exists.

## Environment Information
The required dependencies are all installed into the autometa environment using conda

**Comment by WiscEvan** [comment]
Hi @benjaminjtc, it appears you may be using python 3, when in fact autometa uses python 2.7. Could you try running this in a python2.7 environment and letting me know if this resolves the issue?

**Comment by WiscEvan** [comment]
This issue is stale and I'm going to assume it was resolved by switching to python 2.7.
