### ISSUE TITLE
Use unicycler headers to calculate contig coverage

### ISSUE THREAD

**Issue by Sidduppal** [KwanLab/Autometa#113]
Provide an option to use [Unicycler](https://github.com/rrwick/Unicycler) header to calculate contig coverage. Preferably in [coverage.py](https://github.com/KwanLab/Autometa/blob/dev/autometa/common/coverage.py)
Example of unicycler contig headers:

```bash
>4 length=424287 depth=1.00x
>5 length=365569 depth=1.06x circular=true
```

**Comment by WiscEvan** [comment]
Would be easy to add this flag for the `autometa-coverage` entrypoint as `--from-unicycler` similar to what is being done now with `--from-spades`

**Comment by WiscEvan** [comment]
command to add:

```python
parser.add_argument(
        "--from-unicycler",
        help="Extract coverages from unicycler contig headers. (Input assembly is output from Unicycler)",
        action="store_true",
        default=False,
    )
```


```python
def get_unicycler_coverage():
    ...
```

Will need to handle for when the user specifies this in `def main()`
