### ISSUE TITLE
 Error: file already exists!".format(output_path)

### ISSUE THREAD

**Issue by razz1618** [KwanLab/Autometa#114]
### User checklist

- [x] Are you using the latest release?
- [x] Are you using python 3?
- [x] Did you check previous issues to see if this has already been mentioned?
- [x] Are you using a Mac or Linux machine?

#### Description

I have installed automata with the mentioned dependencies in a conda environment. When I run the test file (as well as my contig file) I get the following error. The same error is repeated when I try to run it via docker. I guess the problem is related to my system and not to automata. As I could not find the help command in automata,, I could not figure out the solution. Hope you might help me with this.  Following is the error message I get

#### System Environment

- Operating System: Centos 0S 7
- RAM: 512GB
- Disk:3000TB (2000TB free)

error:
python make_taxonomy_table.py --assembly /home/mcs/soft/Autometa/test_data/scaffolds.fasta --processors 16 \ --length_cutoff 3000
  File "make_taxonomy_table.py", line 233
    print "{} file already exists!".format(output_path)
                                  ^
SyntaxError: invalid syntax
```

```

</p></details>

**Comment by WiscEvan** [comment]
Hello @razz1618, 

Thank you for reaching out to us. This syntax error is a result of using python 3 instead of python 2. Autometa currently only supports python 2.7. Can you try running Autometa in a python2.7 environment?

**Comment by razz1618** [comment]
Yes, that's correct somehow my conda environment had both version of python (3 and 2.7). Created a new environment with python 2.7. It seems to be working now. Will try further steps. THANKS.
