### ISSUE TITLE
Running in parallel from python or from Nextflow?

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#136]
I'm still not very deep into looking at how things are run parallel from python but have encountered some places where it might make more sense to parallelize in Nextflow rather than from python.
 
A good example is the comment in the python codebase [here](https://github.com/WiscEvan/Autometa/blob/b92cc3577a1fac6ebdb674c29345f8fa44fcb55d/autometa/common/external/hmmer.py#L179) : ` # OPTIMIZE: we want to extend parallel to grid computing (workqueue?) via --sshlogin`

It's pretty trivial to split fasta files into parallel processes in Nextflow and wonder if those cases should be abstracted out of the python code and left for Nextflow?

**Comment by chasemc** [comment]
I think one reason to consider implementing that parallelism in Nextflow is that's easier/faster to request/schedule smaller requests for each parallel task (e.g. 1 cpu and 1GB) than one giant request (e.g. 60 cpu and 60GB) that is further sub-assigned by python

**Comment by WiscEvan** [comment]
Parallel Tasks:

- Prodigal ORF calling
- HMMSCAN
- k-mer counting

**Comment by WiscEvan** [comment]
I've recently come across an error where tasks were split with nextflow and then get concatenated in a process before moving on the the next process in the workflow. Placing this here for possible considerations on what _not_ to do when it comes to splitting these up. I'm assuming I need some nextflow programming for this aggregation?

## The error message

```bash
[96/70be31] process > GENOME_KMERS:COUNT (count GCA_003228875.1_genomic.fna.gz 4-mers) [100%] 31910 of 31910, cached: 31910 ✔
[-        ] process > GENOME_KMERS:AGGREGATE                                           [  0%] 0 of 1

Error executing process > 'GENOME_KMERS:AGGREGATE (Aggregating genome 4-mer counts)'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  sbatch: error: Batch job submission failed: Pathname of a file, directory or other parameter too long
```

## Execution in the workflow

```groovy
AGGREGATE( COUNT.out.collect(), size )
```

## The process

```groovy
process AGGREGATE {
  tag "Aggregating genome ${size}-mer counts"
  publishDir params.interim, mode: 'symlink'

  input:
    path counts
    val size
  
  output:
    path "genome_${size}mers.tsv.gz"
  
  script:
  """
  afmgp-aggregate-counts --input $counts --output genome_${size}mers.tsv.gz --index-col genome
  """
}
```

**Comment by chasemc** [comment]
You probably want to `buffer` the input to the first process, 31910 is a lot of jobs and you probably just want to saturate the cpus with less but bigger jobs? Collecting that many symlinks seems to be the issue:
https://github.com/nf-core/rnaseq/issues/100#issuecomment-427338583
