### ISSUE TITLE
Nextflow and NCBI databases

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#142]
I may have missed it but there's no check in Nextflow for the contents of `"${params.ncbi_database}"`, maybe it's done in the Python code but maybe it would be better to fail sooner from Nextflow?
Also, a single directory for databases means that users will potentially have to have 100's of GB of duplicate databases on their system if they already have the same databases saved somewhere else.  Should it be possible to specify different paths for the different sets of databases?

**Comment by WiscEvan** [comment]
We could add a process at the beginning of the nextflow workflow that checks for these databases. The autometa command for this would be:

```bash
autometa-update-databases --check-dependencies
```

Note: This is mentioned in the documentation branch https://github.com/KwanLab/Autometa/pull/121#discussion_r614245434 on  whether we should rename this entrypoint to `autometa-databases`

```bash
autometa-databases --check-dependencies
```

Written here:
https://github.com/KwanLab/Autometa/blob/dev/autometa/config/databases.py


Users should not have to duplicate their databases on their system. We _could_ add flags to provide each separate database file, but this sounds tedious if having to perform this each time you want to run a metagenome. Although now that we have moved everything to work with nextflow this would be straightforward within the `parameters.config` file, it may not be the nicest when working outside the nextflow environment. To reduce the tedium, we have opted to write to a config file that can be looked up for convenience. You can configure the path to your databases with `autometa-config` -> https://github.com/KwanLab/Autometa/blob/50f7a60c329acfa9e705b4cf343dfdcc21ade0ec/autometa/config/utilities.py#L234-L252

**Comment by chasemc** [comment]
My opinion is that it's nice to have a convenience function that downloads and dumps everything into one folder, but since it's >300Gb this should only be done with active permission from the user. If someone already has the diamond databases in other directories for other projects they may not have the resources to duplicate them into Autometa's-expected single directory. So maybe Nextflow's default would be to have a single directory that it checks, but also give the opportunity for the individual database paths to be provided?

Not to derail, but on this point, is there a place in the documentation for the system requirements of Autometa (e.g. required and suggested disk space, etc.)? @Sidduppal

**Comment by chasemc** [comment]
Duplicate of https://github.com/KwanLab/Autometa/issues/147
