### ISSUE TITLE
Turn off CI for non PR pushes?

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#143]
Current behavior is to run all checks/CI on travis for all pushes. This is true even for forked versions. I think it's fine to only run the checks on a PR/pushes to a PR, and merges to dev or main?

**Comment by jason-c-kwan** [comment]
Worth noting here is that everything fails for `main` right now because all that code is very old, predating all the integrations.

**Comment by WiscEvan** [comment]
So far we are not hitting any limits. Until that becomes an issue, I don't see this as a problem. Anyone making changes should know if their changes are breaking the code
