### ISSUE TITLE
Nextflow pipeline fails if "metagenome.filtered.fna" is used as input

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#146]
If you provide `metagenome.filtered.fna` from one of the example datasets as input to nextflow, the pipeline fails with `FileExistsError: metagenome.filtered.fna`. I'm assuming the python code looks for ".filtered.fna", not sure it's safe to assume a user wouldn't possibly have a file with this.

```
metagenome  : /Users/chase/Downloads/metagenome.filtered.fna

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/opt/conda/bin/autometa-length-filter", line 33, in <module>
      sys.exit(load_entry_point('Autometa==2.0a0', 'console_scripts', 'autometa-length-filter')())
    File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/metagenome.py", line 393, in main
      filtered_mg = raw_mg.length_filter(
    File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/utilities.py", line 438, in wrapper
      obj = func(*args, **kwds)
    File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/metagenome.py", line 303, in length_filter
      raise FileExistsError(out)
  FileExistsError: metagenome.filtered.fna
```

**Comment by chasemc** [comment]
Pipeline initiates if the filename is changed to `metagenome.fna`

**Comment by WiscEvan** [comment]
The python behavior is to prevent overwriting a user's file. This error is only raised if the file exists and they did not pass in `--force` to overwrite the file. I would not consider this a bug. However perhaps this would be considered a bug under the nextflow implementation? SImilarly, we could add a `force` parameter to overwrite any existing files.

**Comment by chasemc** [comment]
Python is modifying the name (adding ".filtered"), so it should just append (".filtered.filtered") rather than fail?

**Comment by chasemc** [comment]
Nevermind, it's nextflow that's adding it
