### ISSUE TITLE
Simple conda requirements and docker image for nextflow pipeline

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#150]
First- I have most all the nextflow stuff in `~/Autometa/nextflow` now, with only a false-config in the main directory `~/Autometa/` so that someone can pull the pipeline directly from nextflow. 

I was thinking of making another, simple requirements.txt and dockerfile within the`/Autometa/nextflow` directory that are specific for running the nextflow pipeline. They would be simple: likely only including `nf-core, nextflow, aspera`. 

The main reason is nextflow and/or nf-core are required to be installed in order for the pipeline to run but I don't think should be in the mostly-python oriented https://github.com/KwanLab/Autometa/blob/dev/requirements.txt

Thoughts?

**Comment by WiscEvan** [comment]
This may be easier to review under a pull request with your code changes. This way the context of your changes and the discussion are all in one place and up to date.

**Comment by chasemc** [comment]
Fixed by https://github.com/KwanLab/Autometa/pull/157
