### ISSUE TITLE
Add nf-core license where necessary

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#159]
https://github.com/nf-core/tools/blob/master/LICENSE

**Comment by WiscEvan** [comment]
Where does this need to go? I noticed in the [minimum requirements section](https://nf-co.re/developers/guidelines#minimum-requirements) to use nf-core is that the pipeline must have an MIT license

**Comment by chasemc** [comment]
A few of the template files that come from nf-core, not a ton of them. MIT is only necessary if submitting to nf-core

**Comment by chasemc** [comment]
I've asked again on the nfcore slack
