### ISSUE TITLE
Do you think it would be worth changing the I/O behavior here s.t. each input metagenome has its own directory?

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#160]
Do you think it would be worth changing the I/O behavior here s.t. each input metagenome has its own directory? 

Maybe we change this to output to follow nf-core guidelines (one `--input` arg. and one `--output` arg) to specify where results should be placed.

The proposed `--output` directory structure:

```bash
-- output/
    +-- input_metagenome_1
    │   \-- kmer results related to metagenome_1
    │   \-- binning results related to metagenome_1
    │   \-- ... etc.
    +-- input_metagenome_2
    │   \-- ... files related to metagenome_2
    \-- etc.
```

_Originally posted by @WiscEvan in https://github.com/KwanLab/Autometa/pull/157#r636964912_

**Comment by chasemc** [comment]
Do you mean "..each input metagenome has its own *output* directory?"

I do think that's probably the way to go.

**Comment by WiscEvan** [comment]
> Do you mean "..each input metagenome has its own _output_ directory?"
> 
> I do think that's probably the way to go.

Yes, so results from each directory could be collected for pan-genome binning and it would be intuitive to find results specifically for any individual metagenome.

**Comment by WiscEvan** [comment]
[Example template](https://nf-co.re/mag/usage#samplesheet-input-file) as used by MAG in nf-core pipelines

**Comment by chasemc** [comment]
Just pushed a really large commit (https://github.com/KwanLab/Autometa/commit/378789f8c2e2081c4e0c7ba8c23c7b608501983a) that implements nf-core's DSL-2 pipeline based structure. And I've got multi-sample (currently only multiple contig fasta input files) mostly working (have to fix some publishdirs)

**Comment by chasemc** [comment]
No sample map currently needed but I think will become important with incorporating reads and assemblies or just reads.

**Comment by WiscEvan** [comment]
See also #188
