### ISSUE TITLE
MultiQC

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#163]
Some of the as-yet-unused nf-core template is some MultiQC stuff. We can either go ahead and incorporate it or remove these files. 

https://multiqc.info/

**Comment by chasemc** [comment]
https://github.com/KwanLab/Autometa/pull/157/files#r637044735

**Comment by chasemc** [comment]
ping @jason-c-kwan @WiscEvan @Sidduppal

**Comment by WiscEvan** [comment]
:fire: I vote for removing the multiQC/fastQC stuff, as Autometa was implemented for binning, not assembly/QC

**Comment by Sidduppal** [comment]
Yeah, I think we should remove fastQC/multiQC.
