### ISSUE TITLE
Add params.publish_dir_mode

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#164]
Should all of these processes be updated with `params.publish_dir_mode` as well?

_Originally posted by @WiscEvan in https://github.com/KwanLab/Autometa/pull/157#r636270185_

**Comment by chasemc** [comment]
For all nextflow **processes** with a "publishDir" add an additional parameter params.publish_dir_mode


@ajlail98 If you have the time and wanted to take a stab at this you could create branch off the nfcore  branch and then make a pr back onto the nfcore branch. Additional info below:

example:
https://github.com/KwanLab/Autometa/blob/9dc0f7b7b86f984c6bf154196d2e602457eca258/nextflow/modules/autometa_core/contig_binning/process/binning.nf#L7

would become 

`  publishDir params.outdir, pattern: "${coverage.simpleName}.${params.kingdom}.*.tsv.gz", mode: params.publish_dir_mode`


https://www.nextflow.io/docs/latest/process.html?highlight=publishdir#publishdir

**Comment by WiscEvan** [comment]
- [MAG publish_dir mode example](https://github.com/nf-core/mag/blob/0b4f0ef116481a346e3e5ffebafb811872db2ba9/modules/local/bowtie2_assembly_align.nf#L10-L12)

**Comment by chasemc** [comment]
Fixed by https://github.com/KwanLab/Autometa/pull/157
