### ISSUE TITLE
Add metagenome name to tags

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#165]
May be nice to tag this with the current dataset name instead of a generic phrase

_Originally posted by @WiscEvan in https://github.com/KwanLab/Autometa/pull/157#r636272686_

**Comment by chasemc** [comment]
duplicate of #160

**Comment by chasemc** [comment]
Fixed in https://github.com/KwanLab/Autometa/pull/157/commits/73bdfc6caadd500e94e4c980d712a0a5440be46d

**Comment by WiscEvan** [comment]
Should this be closed as a duplicate of #160? or am I missing something?

**Comment by chasemc** [comment]
It's the tags that display the currently-running sample id on the command line while the pipeline is running

Closed because complete and not a duplicate of 160.
