### ISSUE TITLE
Error while installib tsne with conda

### ISSUE THREAD

**Issue by Unaimend** [KwanLab/Autometa#179]
# Current Behavior
Error while installing tsne

## Steps to Reproduce

```bash
conda install -c maxibor tsne

```

# Expected Behavior

## Environment Information

<details>

conda 4.10.3
Python 2.7.15
```bash
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
bedtools2                 2.25.0                        0    zechxu
biopython                 1.76             py27h516909a_0    conda-forge
blas                      1.1                    openblas    conda-forge
boost-cpp                 1.74.0               h312852a_4    conda-forge
bowtie2                   2.3.5.1          py27he513fc3_0    bioconda
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
cython                    0.29.24                  pypi_0    pypi
diamond                   2.0.11               hdcc8f71_0    bioconda
hmmer                     3.3.2                h1b792b2_1    bioconda
htslib                    1.12                 h9093b5e_1    bioconda
icu                       68.1                 h58526e2_0    conda-forge
joblib                    0.13.2                   py27_0    anaconda
krb5                      1.19.1               hcc1bbae_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_1    conda-forge
libblas                   3.9.0           1_h6e990d7_netlib    conda-forge
libcblas                  3.9.0           3_h893e4fe_netlib    conda-forge
libcurl                   7.77.0               h2574ce0_0    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.5.0               h14aa051_19    conda-forge
libgfortran4              7.5.0               h14aa051_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
liblapack                 3.9.0           3_h893e4fe_netlib    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.16.5           py27h95a1406_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pandas                    0.24.2           py27hb3f55d8_0    conda-forge
perl                      5.32.1          0_h7f98852_perl5    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
prodigal                  2.6.3                h779adbc_3    bioconda
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2019.3                     py_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
samtools                  1.12                 h9aed4be_1    bioconda
scikit-learn              0.19.2          py27_blas_openblasha84fab4_201  [blas_openblas]  conda-forge
scipy                     1.2.1            py27h921218d_2    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h9cd32fc_0    conda-forge
tbb                       2021.3.0             h4bd325d_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tqdm                      4.61.2             pyhd8ed1ab_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge

```

</p></details>

## Run Information
```bash
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
                                                                       n
Specifications:

  - tsne -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']

Your python: python=2.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow                                                        o
not available for the python version you are constrained to. Note that pconda will not
change your python version to a different minor version unless you explicitly specify                                                         m
that.                                                                  w

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - python=2.7 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - tsne -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
                                                                       m
Your installed version is: 2.17                                        w

```

**Comment by Unaimend** [comment]
Error from autometa when running it
  ```bash
  File "/work_beegfs/sukem127/module_binaries/autometa/Autometa/pipeline/recursive_dbscan.py", line 32, in <module>
    from tsne import bh_sne
ImportError: No module named tsne
```

**Comment by WiscEvan** [comment]
Hi Thomas, Thank you for bringing this to our attention. As you may suspect, tsne now only supports python 3. I've just submitted a pull request from the [2to3 branch](https://github.com/KwanLab/Autometa/tree/2to3) that will update the pipeline to using python 3. You should be able to get autometa installed from this branch until this gets merged into main. 

From here installation is much simpler:

```bash
## Get the 2to3 branch
git clone https://github.com/KwanLab/Autometa.git --branch 2to3
cd Autometa
## Create conda autometa environment
conda create -n autometa -c bioconda -c conda-forge python=3.7 --file=requirements.txt
## Activate your autometa environment
conda activate autometa
## Setup lca functions
cd pipeline
python setup_lca_functions.py build_ext --inplace
## Setup HMM databases
cd -
hmmpress -f single-copy_markers/Bacteria_single_copy.hmm 
hmmpress -f single-copy_markers/Archaea_single_copy.hmm
```

From here you may continue with NCBI databases. Please do not hesitate to let us know if you are running into further issues.

Alternatively you could construct an autometa docker image 

```bash
## Get the 2to3 branch and build docker image
git clone https://github.com/KwanLab/Autometa.git --branch 2to3
cd Autometa
docker build . -t jason-c-kwan/autometa:2to3
```

**Comment by Unaimend** [comment]
Thank you very much for the quick support, what exactly do you mean by "From here you may continue with NCBI databases" because I am using Autometa on our HPC cluster and the compute nodes sadly do not have internet, which I circumvented by letting autmeta run until the Diamond Database was downloaded and then restarted it on a compute node. Sadly, I also cannot use Docker as I do not have root permissions on the cluster

**Comment by WiscEvan** [comment]
Okay, good to know. We can circumvent your issues with internet and docker by ensuring you have properly configured your Autometa environment and necessary databases.

## Autometa environment

As long as you have the Autometa environment properly configured, you should be able to easily perform the database configuration steps as well. You should be able to configure an autometa environment following the instructions from the [previous comment](https://github.com/KwanLab/Autometa/issues/179#issuecomment-887648050)

## Circumventing no internet

The links to the necessary databases can be found here: https://autometa.readthedocs.io/en/latest/databases.html

Briefly you will need to perform the following prior to using the HPC cluster (assuming you have no internet)

```bash
# First set up databases directory and sub-directories
cd $HOME
mkdir -p databases/{markers,ncbi}
NCBI_DIR="$HOME/databases/ncbi"
# NOTE: links retrieved from the autometa.readthedocs.io databases link above

# NR Database
## retrieve NCBI non-redundant protein database
wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz -O "${NCBI_DIR}/nr.gz"
## Build with diamond
diamond makedb --in "${NCBI_DIR}/nr.gz" --db "${NCBI_DIR}/nr"
#NOTE: The above will take some time

# Retrieve protein accession to taxid translations
wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz -O "${NCBI_DIR}/prot.accession2taxid.gz"

# Retrieve taxonomy dumps tarball
wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz -O "${NCBI_DIR}/taxdump.tar.gz"
cd $NCBI_DIR
tar -xvzf taxdump.tar.gz
cd -
```

___

## Try Autometa v2-alpha

I also would like to note, we are nearing our 2.0 release so if you would like to try this out you can follow the documentation on [https://autometa.readthedocs.io/](https://autometa.readthedocs.io/). I would recommend following [installation using `make`](https://autometa.readthedocs.io/en/latest/install.html#install-from-source-using-make). 

NOTE: At the beginning `git clone` step, you will need to provide:

```bash
# This will ensure you are working from the development branch (2.0 edge branch)
git clone --branch dev https://github.com/KwanLab/Autometa.git
# .. proceed with installation commands
```

By using the 2.0 branch, you can follow along with the rest of the documentation. We would appreciate feed back on our step-by-step tutorial: https://autometa.readthedocs.io/en/latest/step-by-step-tutorial.html#

Please let me know if you have any other questions!

**Comment by Unaimend** [comment]
Thank you very much for your detailed help, this is by far the best support I have ever received. I will try the installation of (autometa v1 and autometa v2) tomorrow.

**Comment by Unaimend** [comment]
I have followed all the steps you mentioned, especially 
```
wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz -O "${NCBI_DIR}/prot.accession2taxid.gz"
```
but when I run autometa I get this error
```
make_taxonomy_table.py, run_command: python setup_lca_functions.py build_ext --inplace
acc2taxid database not found, downloading/formatting.
                                This may take some time...
updating prot.accession2taxid
```
Which then results in autometa trying to download the database, which it cannot do because it does not have internet, while still overwriting the existing 6gb databse with an empty file

**Comment by WiscEvan** [comment]
Hi Thomas, It looks like there was a minor bug when performing database checks in `make_taxonomy_table.py`. It was expecting the gunzipped `prot.accession2taxid` file rather than `prot.accession2taxid.gz`. I've updated the code to allow for this (using the compressed version will help with disk space as well, nice catch 👍). You can update the `2to3` branch using the `git pull` command.

```bash
# Assuming you have already performed these steps:
# git clone https://github.com/KwanLab/Autometa.git --branch 2to3
# cd Autometa
git pull origin 2to3
```

**Comment by Unaimend** [comment]
There seems to be another error
```bash
  File "/work_beegfs/sukem127/module_binaries/Autometa/pipeline/run_autometa.py", line 411, in <module>
    logger = init_logger(autometa_path, db_dir_path, output_dir)
  File "/work_beegfs/sukem127/module_binaries/Autometa/pipeline/run_autometa.py", line 59, in init_logger
    prog_version = subprocess.check_output([prog, "--version"]).split("\n")[0]
TypeError: a bytes-like object is required, not 'str'
```

**Comment by Unaimend** [comment]
https://stackoverflow.com/questions/44989808/subprocess-typeerror-a-bytes-like-object-is-required-not-str 

This could be helpful, if I have time I will try it myself later

**Comment by Unaimend** [comment]
Same Error at line 65 
```
 File "/work_beegfs/sukem127/module_binaries/Autometa/pipeline/run_autometa.py", line 411, in <module>
    logger = init_logger(autometa_path, db_dir_path, output_dir)
  File "/work_beegfs/sukem127/module_binaries/Autometa/pipeline/run_autometa.py", line 65, in init_logger
    subprocess.check_output(["hmmpress", "-h"]).split("\n")[1].replace("# ", "")
TypeError: a bytes-like object is required, not 'str'
```


But it seems I was able to fix the this error 
> There seems to be another error
> 
> ```shell
>   File "/work_beegfs/sukem127/module_binaries/Autometa/pipeline/run_autometa.py", line 411, in <module>
>     logger = init_logger(autometa_path, db_dir_path, output_dir)
>   File "/work_beegfs/sukem127/module_binaries/Autometa/pipeline/run_autometa.py", line 59, in init_logger
>     prog_version = subprocess.check_output([prog, "--version"]).split("\n")[0]
> TypeError: a bytes-like object is required, not 'str'
> ```
by changig this line 
```prog_version = subprocess.check_output([prog, "--version"]).split("\n")[0]```
to
```
prog_version = subprocess.check_output([prog, "--version"], text=True).split("\n")[0]
```

**Comment by Unaimend** [comment]
> Okay, good to know. We can circumvent your issues with internet and docker by ensuring you have properly configured your Autometa environment and necessary databases.
> 
> ## Autometa environment
> As long as you have the Autometa environment properly configured, you should be able to easily perform the database configuration steps as well. You should be able to configure an autometa environment following the instructions from the [previous comment](https://github.com/KwanLab/Autometa/issues/179#issuecomment-887648050)
> 
> ## Circumventing no internet
> The links to the necessary databases can be found here: https://autometa.readthedocs.io/en/latest/databases.html
> 
> Briefly you will need to perform the following prior to using the HPC cluster (assuming you have no internet)
> 
> ```shell
> # First set up databases directory and sub-directories
> cd $HOME
> mkdir -p databases/{markers,ncbi}
> NCBI_DIR="$HOME/databases/ncbi"
> # NOTE: links retrieved from the autometa.readthedocs.io databases link above
> 
> # NR Database
> ## retrieve NCBI non-redundant protein database
> wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz -O "${NCBI_DIR}/nr.gz"
> ## Build with diamond
> diamond makedb --in "${NCBI_DIR}/nr.gz" --db "${NCBI_DIR}/nr"
> #NOTE: The above will take some time
> 
> # Retrieve protein accession to taxid translations
> wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz -O "${NCBI_DIR}/prot.accession2taxid.gz"
> 
> # Retrieve taxonomy dumps tarball
> wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz -O "${NCBI_DIR}/taxdump.tar.gz"
> cd $NCBI_DIR
> tar -xvzf taxdump.tar.gz
> cd -
> ```
> 
> Now simply transfer the `databases` directory to your compute node with your autometa configuration specifying `databases/ncbi` as the ncbi database directory and you should be good to go.
> 
> ## Try Autometa v2-alpha
> I also would like to note, we are nearing our 2.0 release so if you would like to try this out you can follow the documentation on https://autometa.readthedocs.io/. I would recommend following [installation using `make`](https://autometa.readthedocs.io/en/latest/install.html#install-from-source-using-make).
> 
> NOTE: At the beginning `git clone` step, you will need to provide:
> 
> ```shell
> # This will ensure you are working from the development branch (2.0 edge branch)
> git clone --branch dev https://github.com/KwanLab/Autometa.git
> # .. proceed with installation commands
> ```
> 
> By using the 2.0 branch, you can follow along with the rest of the documentation. We would appreciate feed back on our step-by-step tutorial: https://autometa.readthedocs.io/en/latest/step-by-step-tutorial.html#
> 
> Please let me know if you have any other questions!


Also in this description it seems to me that you for got to download the .md5
```shell
wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz -O "${NCBI_DIR}/nr.gz"
```

And I think autometa tries to redownload the whole database file if it does find the correct md5 is that corrent?

**Comment by WiscEvan** [comment]
Hi Thomas, thanks for the suggestions! I have updated [the 2to3 branch](https://github.com/KwanLab/Autometa/tree/2to3) with the `subprocess.check_output(..., text=True)` parameter. I have applied these changes across the pipeline.

### md5 checks and Autometa databases

I apologize for missing the md5 downloads. Autometa will only look for these md5 files if the directory containing these databases matches the default Autometa databases directory (`Autometa/databases`). For example,

```bash
# This directory will be checked for md5s
$HOME/Autometa/databases
# This will not be check for md5s
$HOME/autometa_databases
```

#### default `PIPELINE` and `AUTOMETA_DATABASES` variables

This is outlined in line 43:

https://github.com/KwanLab/Autometa/blob/0dc84b544207deda17e51006f30050fde3bc4039/pipeline/make_taxonomy_table.py#L42-L43

#### Example of default `PIPELINE` and `AUTOMETA_DATABASES` variables

```bash
(autometa) ➜  Autometa git:(2to3) python pipeline/make_taxonomy_table.py 
> /Users/rees/Wisc/kwan/for_thomas/Autometa/pipeline/make_taxonomy_table.py(47)<module>()
-> def run_command(command_string, stdout_path=None):
(Pdb) AUTOMETA_DATABASES
'/Users/rees/Wisc/kwan/for_thomas/Autometa/databases'
(Pdb) PIPELINE
'/Users/rees/Wisc/kwan/for_thomas/Autometa/pipeline'
```

#### File checks depending on database directory path

and lines 243-254:

https://github.com/KwanLab/Autometa/blob/0dc84b544207deda17e51006f30050fde3bc4039/pipeline/make_taxonomy_table.py#L243-L254

**Comment by jason-c-kwan** [comment]
Hi Thomas,

Just an update - we are still working on this but the need to convert from Python 2 to 3 is turning out to be more complicated than we initially thought. We are still testing but it should be finished soon.

Thanks for your patience.

**Comment by Unaimend** [comment]
No problem, I thank you for your effort. I will try to test your latest changes to the branch this weekend.
And maybe its presumptuous to as this, but did you look into using mypy. I think it's a great way for making python projects more resilient to bugs.
Anyway, I have a few more questions regarding autometa and your publication in general, I hope it's fine to ask them here? Or do your prefer to use another mean of communication to not clutter this issue with irrelevant stuff?

**Comment by jason-c-kwan** [comment]
Hi Thomas,
Thanks for the suggestion - I would say that we _are_ putting a lot more effort into developing V2 into a more robust program (it is completely refactored and includes a lot better design principles - even unit test), and that is why V1 is a little bit of a mess. If you want to test that you could check out the dev branch although I should warn you that the documentation is not finished yet. Having said that, I think with this PR it should make v1 functional in Python 3. For your more general questions, feel free to e-mail me using the email address on the paper (I don't want to encourage more spam by putting it here).
