### ISSUE TITLE
[Dev branch] Issues with autometa/common/external/bedtools.py

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#18]
This is a script which contains wrapper functions for running [https://bedtools.readthedocs.io/en/latest/](Bedtools) and parsing the results.

Issues:

1. The `genomecov` function doesn't return anything, so this should be stated in the docstring.

2. If the `out` path already exists, then the `genomecov` function raises a FileExistsError. However, it would be good to perhaps have a `force` flag so that it will go ahead and overwrite? Otherwise if something goes wrong in the middle of this step, it is difficult to re-run without manually deleting the file. An alternative would be to add code that deletes the output file in the event of `retcode` coming back as not equal to zero.

3. As a first step in the `parse` function, it checks whether the `out` path exists, and if so it will parse as a Pandas dataframe and return that. However, there is no code to check whether the table is valid. Perhaps the error-handling within Pandas is enough?

4. The `parse` function loads the `.bed` file as a Pandas dataframe with the following column names: `contig`, `depth`, `bases`, `length`, `breadth`. However, according to the [https://bedtools.readthedocs.io/en/latest/content/tools/genomecov.html](the Bedtools docs), the last column is the fraction of bases on the chromosome (contig in this case) with depth equal to column 2, so the name `breadth` is perhaps not very descriptive.

https://github.com/KwanLab/Autometa/blob/01a432d97044be6522b969a6495be61aeffa2ba7/autometa/common/external/bedtools.py#L102-L103

5. Likewise I am not sure the name `total_breadth` is appropriate for this variable:

https://github.com/KwanLab/Autometa/blob/01a432d97044be6522b969a6495be61aeffa2ba7/autometa/common/external/bedtools.py#L107-L109

**Comment by WiscEvan** [comment]
I'm taking this on, as I've found a line that has implications in #21 (which I'm already working on).

**Comment by WiscEvan** [comment]
@jason-c-kwan What would you prefer the column names (`breadth` and `total_breadth` to be?

I was referencing [this](https://www.danielecook.com/calculate-depth-and-breadth-of-coverage-from-a-bam-file/) when naming the columns.
