### ISSUE TITLE
One thing I'm encountering/fixing now on the nfcore/dev branch is that MAKE on Mac doesn't work because 2.7 is the default python. You will need to change the `python` calls to `python3` in the MAKEFILE

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#183]
One thing I'm encountering/fixing now on the nfcore/dev branch is that MAKE on Mac doesn't work because 2.7 is the default python. You will need to change the `python` calls to `python3` in the MAKEFILE

_Originally posted by @chasemc in https://github.com/KwanLab/Autometa/issues/180#issuecomment-888683790_

**Comment by WiscEvan** [comment]
It looks like all of the python calls have been changed to python3 for the relevant makefile commands.
