### ISSUE TITLE
Add read-based contig coverage instead of spades-based

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#186]
Partially implemented subworkflow needs to be updated to nf-core 2 format
https://github.com/KwanLab/Autometa/blob/8934bf52ae7ab4b91018b0cfc9020f50280fd201/subworkflows/local/contig_coverage.nf

**Comment by WiscEvan** [comment]
What else needs to be updated/implemented for this subworkflow?

**Comment by chasemc** [comment]
Been awhile but I don't think reads are considered at all yet because it was extra complication switching the existing subworkflow to the metamap format.

We'll have to decide on the best input format first. My vote would be to start with tsv: https://nf-co.re/mag/2.1.0/usage#samplesheet-input-file
