### ISSUE TITLE
[Dev branch] Issues with autometa/common/external/samtools.py

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#19]
This file contains wrapper functions for samtools (so converting a sam alignment file to a sorted bam and calculating the read depth).

Issues:

1. In the `if __name__ == '__main__':` block, the argparse block doesn't contain any documentation as to what the program does or what the command line arguments are. 

2. The `main` function calls a function that is not implemented (`depth`, see below).

3. The `sort` function takes three arguments, `sam`, `out` and `nproc=0`, meaning that the default value for `nproc` is zero if it is not specified. I couldn't find anything in the samtools documentation about what happens when you specify zero processors, so it would be better to explicitly state this in a comment or perhaps change the default value. The function should probably also have a docstring.

4. The `depth` function is not implemented and it raises a NotImplementedError. It also does not have a docstring to explain, for example, what type of object `records` should be. (It looks like it could be a list of BioPython SeqRecords). Without a docstring it is unclear why this function is needed when we have the functions in bedtools.py.

5. The `run` function seems to handle the running of external programs in this script. It takes a string which is interpreted as a command by `subprocess.call`. The stdout and stderr are both directed to `os.devnull`. One glaring problem with this function are the return values. In Unix operating systems all programs return a value, and by convention it is zero if the program was successful and nonzero if not (the exact value will be specific to the type of error for that program). In programming languages, numbers can be cast as bools, with `0`, `None` or `undef` evaluating as `False` in Python (and many other languages), while nonzero evaluates as `True`. What this function does is exactly the opposite. If `retcode == 0` then it returns `True` and if `retcode != 0` it returns `False`. While this may seem intuitive, it is exactly the opposite of what most programmers will assume, and so I strongly advise that this is changed.

**Comment by Sidduppal** [comment]
@WiscEvan, inquiring the 4th point of this issue. I couldn't find the `depth`  function being called by any other script. The function is supposed to use samtools to computes the read depth at each position or region, however, it is not being implemented.
Should I remove it?

**Comment by WiscEvan** [comment]
Yes, you could remove it for now.
