### ISSUE TITLE
Create GitHub Action for building and publishing docker images

### ISSUE THREAD

**Issue by WiscEvan** [KwanLab/Autometa#191]
Create a GitHub Action that builds and publishes docker images by tracking git branches.

Tracking branches:

- `main`
- `dev`

Events that trigger action:

```yml
# Triggers the workflow on push or pull request events
on: [push, pull_request]
```

- 🔗  [setup new workflow](https://github.com/KwanLab/Autometa/new/main?filename=.github%2Fworkflows%2Fdocker-publish.yml&workflow_template=docker-publish "GitHub")
- :link: [events that trigger workflow](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows)
- 🔗  [metadata-action](https://github.com/docker/metadata-action) - GitHub Action to extract metadata from Git reference and GitHub events
- 🔗  [docker-build-push action](https://github.com/docker/build-push-action) - GitHub Action to build and push Docker images

**Comment by chasemc** [comment]
There's also an error in the pipeline

Lot's of `jason-c-kwan/autometa` as the docker image because I copied from the makefile.  They all need to be changed to `jasonkwan/autometa`
