### ISSUE TITLE
Should prodigal be inside of the taxonomy aware if statement?

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#199]
https://github.com/KwanLab/Autometa/blob/92179f561a1e4672fa4ab9b4ecd62f2a544c8e44/workflows/autometa.nf#L141-L161

**Comment by WiscEvan** [comment]
ORFs are required for marker annotation which is necessary with or without using taxon assignments. So that would be a no. 👍

**Comment by chasemc** [comment]
Rightttt. I knew there was somewhere else. @ajlail98 and I were going through stuff over the break and I was 🥴
