### ISSUE TITLE
python2.7 BH-SNE

### ISSUE THREAD

**Issue by WiscEvan** [KwanLab/Autometa#2]
Another implementation of py2.7 bh_sne

**Comment by ijmiller2** [comment]
Have you guys considered using [UMAP](https://github.com/lmcinnes/umap)? Recently discovered it through a collaborative project. It seems to have worked well with some our multi-comics data integration and apparently it has some advantages over t-SNE, e.g. [quoting a post on Medium](https://medium.com/@dan.allison/dimensionality-reduction-with-umap-b081837354dd).

"
...
However, UMAP appears to have some significant advantages over t-SNE:
- It’s faster than t-SNE.
- It captures global structure better than t-SNE.
- Best of all, while t-SNE doesn’t have much use outside of visualization, UMAP is a general-purpose dimensionality reduction technique that can be used as preprocessing for machine learning.
- UMAP also has a solid theoretical backing as a manifold approximation technique, whereas t-SNE is primarily a visualization heuristic.  

...  
"

Side note - interesting paper recently published on a similar algorithm, [TMAP](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-020-0416-x). It's also implemented in Python and has an interesting use case with the [Natural Products Atlas](http://tmap.gdb.tools/src/npatlas/index.html)

**Comment by WiscEvan** [comment]
Yes, UMAP is already implemented in the refactored version. Feel free to check it out [here](https://github.com/KwanLab/Autometa/blob/dev/autometa/common/kmers.py)

**Comment by ijmiller2** [comment]
Oh, nice! Well that TMAP paper might be worth a read over. They claim to have some significant improvements to the algorithm in run time, general performance, and reproducibility.

**Comment by WiscEvan** [comment]
[bhsne](https://github.com/KwanLab/Autometa/blob/dev/autometa/binning/bhsne.py) implementation from python2.7 that follows similar embedding logic to [kmers.py](https://github.com/KwanLab/Autometa/blob/dev/autometa/common/kmers.py)

**Comment by jason-c-kwan** [comment]
Can this be closed now that we have the updated `tsne` module done by @WiscEvan ?

**Comment by WiscEvan** [comment]
I was planning on closing this once the [tsne PR](https://github.com/conda-forge/staged-recipes/pull/11310) has been added to conda-forge.

**Comment by WiscEvan** [comment]
Closing because conda-forge/staged-recipes#11310 was merged
