### ISSUE TITLE
Wrong contigs used when taxonomy aware == true

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#200]
When running "taxonomy-aware", binning currently uses all contigs instead of the split kingdoms contigs

https://github.com/KwanLab/Autometa/blob/92179f561a1e4672fa4ab9b4ecd62f2a544c8e44/workflows/autometa.nf#L221-L222

Will be addressed at the same time as https://github.com/KwanLab/Autometa/issues/185

**Comment by WiscEvan** [comment]
As far as I can tell it is. It is not the most elegant solution, but for now I believe it works just fine. If the user wants to bin both archaea and bacteria, they will need to specify a separate `params.outdir` so some of the output files do not get overwritten by the specific kingdom.
