### ISSUE TITLE
Add helpful error message for missing module docker image

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#219]
Add helpful error message if module's docker isn't available (e.g. "Try to running `make modules-images` then running nextflow again")

To prevent just seeing:

`Unable to find image 'jasonkwan/autometa-nf-modules-mock_data_reporter:latest' locally`

**Comment by WiscEvan** [comment]
This issue should be resolved once #216 is merged. These images will be hosted after Jason adds his docker credentials.

**Comment by chasemc** [comment]
That makes sense
