### ISSUE TITLE
[Dev branch] Document update needed

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#22]
For the 2.0 release, we need to get the documentation up to date and significantly more friendly for non-technical people to understand. The quality of documentation goes a long way to increasing how much an application is used, which also increases citations for us and general interest. 

I discussed this briefly with @WiscEvan and it would probably be best to use [https://readthedocs.org/](readthedocs), because the information we want to include is probably too much for one README file. This has the advantage that it has versioning and is tied to the github repo. So you would update the docs in the same pull request as your feature update.

Some things that the docs should include:

* Detailed installation instructions, including using Docker and conda (when available)

* Step by step instructions of what to do with an assembly to get bins, and the rationale for choosing different options/parameters.

* How to critically assess the results with R or the web interface (when available). 

Note: I think this is a good issue for someone to work on if they are not yet confident enough in coding to tackle the other issues, and writing documentation is a good way to get an understanding of the pipeline. The language should be friendly and straight forward as possible.

**Comment by jason-c-kwan** [comment]
Should also mention that this should probably serve as both user and API-level documentation, so that others can use our functions and objects etc., and so that it is easy for people to become contributors. Discussed this earlier with @WiscEvan and he will create a shell/table of contents to help others contribute to this issue.

**Comment by jason-c-kwan** [comment]
Also, I can share my notes from the code review when done, for whoever takes this up.

**Comment by jason-c-kwan** [comment]
My notes are here on the server: `/home/jkwan/Autometa_code_review/2020-02-10_Autometa_code_review.ipynb`. I will update periodically.

**Comment by WiscEvan** [comment]
For reference when writing read the docs: [Sphinx and RST syntax guide (0.9.3)](https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html)

**Comment by jason-c-kwan** [comment]
Since I've now finished the code review, I have updated my Jupyter notebook notes, same location as above.
