### ISSUE TITLE
Rename "autometa_website" to "website"

### ISSUE THREAD

**Issue by chanana** [KwanLab/Autometa#23]
**Request:** Rename the django project to `website` instead of `autometa_website`. 
**Reason:** The addition of the extra word is unnecessary; it *is* inside the Autometa directory so it doesn't need an additional qualifier.
**Expected outcome:** More clarity, less clutter

**Comment by chanana** [comment]
### Fixed!

**Comment by WiscEvan** [comment]
Reference to fix below:

Fixed - https://github.com/chanana/Autometa/commit/c81dd023b8355e3f3e0743f54a6cf63efd32fe6a
