### ISSUE TITLE
No markers found - attempts made to find/count kmers

### ISSUE THREAD

**Issue by samche42** [KwanLab/Autometa#237]
Issue: If markers can't be found for a specific dataset, it skips the dataset (awesome). However, it seems that the program still tries to find kmers from the datasets in the next step and then fails. 

I had five of what I call "naughty" datasets where no markers could be found. They were ignored but then Autometa fell on its face during the kmer step. I removed those datasets from the sample sheet and re-ran it. Autometa ran perfectly with the remaining two datasets. 

Suggested fix: Datasets with no markers should be ignored in all downstream processes and reported as failed at the end. Datasets that are ok should be allowed to complete.

**Comment by WiscEvan** [comment]
Can you also place some example error output here for context/testing/troubleshooting?

**Comment by samche42** [comment]
You can go ahead and remove this issue. I updated Autometa (I.e. replaced my nf-core env with the autometa-nf env) and couldn't recreate the problem. Assuming I just had an old bit of code floating around somewhere :)
