### ISSUE TITLE
Quickstart README.md

### ISSUE THREAD

**Issue by WiscEvan** [KwanLab/Autometa#24]
## Dev portion

- [ ] Running an instance locally
- [ ] How to access user dataset for visualization/manipulation
- [ ] Basic steps to start writing a new page (binning exploration, summary, etc.) for a user view
- [ ] Integrate WEBSITE_README.md into existing docs

## User portion

- [ ] User sign-up/sign-in
- [ ] Uploading a results file
- [ ] Exploring Autometa binning results
- [ ] Binning summary breakdown

**Comment by chanana** [comment]
@WiscEvan, when you say:
> How to access user dataset for visualization/manipulation

What exactly do you mean?

**Comment by WiscEvan** [comment]
Checkboxes under the user portion will be points we will need to go through for a tutorial of the interface.

Checkboxes under the dev portion will be points we will need to go through for a tutorial of setting up autometa on one's own instance or computing grid.
