### ISSUE TITLE
API

### ISSUE THREAD

**Issue by WiscEvan** [KwanLab/Autometa#31]
Checklists & Notes
==============

User Registry Service
-------------------------------------------
1. New Users
2. New Projects
3. Upload datasets
4. Upload results

Dataset/Job Registry Service
-------------------------------------------
1. Submission
2. Queries
3. Status/Progress

## Integration:
Hosted on CHTC as prescribed by the proposal:
*"For this reason, we will purchase a dedicated high memory computation node, which will be maintained and administered by the Center for High Throughput Computing at UW–Madison. The Kwan group will be granted priority access to the node for a minimum of three years (see Miron Livny letter)."*

To integrate with grid computing systems such as HTCondor at CHTC, I am initially thinking of using [WorkQueue](http://ccl.cse.nd.edu/software/workqueue/) from Purdue's [Cooperative Computing Lab](http://ccl.cse.nd.edu/).

## Formatting Notes & Resources

API formatting conventions will needs to be put in place for future development, therefore we could rely on GET and POST requests following the semantics of a REST API (See [REST Resource Naming Guide](https://restfulapi.net/resource-naming/)).

- [REST Tutorial](https://restfulapi.net/)
- [Postman](https://www.getpostman.com/downloads/): an API development environment tool
- A minimal API [example](https://flask-restful.readthedocs.io/en/latest/quickstart.html#a-minimal-api) using FLASK-RESTFUL
- [responses status code guide](https://www.restapitutorial.com/httpstatuscodes.html)

Generating Unique IDs [reference](https://www.callicoder.com/distributed-unique-id-sequence-number-generator/)

## We would like to check all five items:

1. Authentication guide ☑
2. Quickstart guide ☑
3. Endpoint definitions ☑
4. Code snippets ☑
5. Example responses ☑

**References and API Ideas**

- [Stripe API Guide](https://stripe.com/docs/api?lang=python)
- [GitHub API Guide](https://developer.github.com/v3/guides/getting-started/)
- [Twilio API Guide](https://www.twilio.com/docs/usage/api)

**API Docs Stretch Goals**

- [8 features](https://nordicapis.com/8-tiny-api-docs-tweaks-that-deliver-big-on-dx/)

**Comment by jason-c-kwan** [comment]
Yeah, I know it says that in the proposal, but we may end up buying our own server to use outside, because with CHTC you only get to use it for 3 years.

**Comment by WiscEvan** [comment]
@chanana okay to close this? I think #32 is likely going to be the spot for updates, do you agree?

**Comment by chanana** [comment]
Yes!
