### ISSUE TITLE
[Dev branch] Issues with autometa/taxonomy/ncbi.py

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#33]
This file contains the logic for handling the NCBI taxonomy databases. Presumably an equivalent would have to be made if we add other alternate taxonomies, like GTDB. I found the following issues in this file:

1. [x] It would be useful if the script's docstring stated that the file contains the definition of the `NCBI` class. At present it just says "Utilities file containing functions useful for handling NCBI taxonomy databases".

2. [x] At the top of the script a few constants are defined, `BASE_DIR`, which is the folder that contains the autometa folder, and `NCBI_DIR` which is defined as `BASE_DIR/databases/ncbi`. I just wanted to check if this is intended? I think I saw somewhere else that the default database directory is supposed to be INSIDE the autometa folder, rather than at the same level?

3. [ ] ~~In the `if __name__ == '__main__':` block, there is a description of the `--query-taxid` argument, but I don't think it adequately explains to the user what this is or what it does.~~

4. [x] In the `__init__` method, I am wondering if the `self.disable` variable is needed or ever used? It seems to be defined as `not self.verbose`, meaning that if `self.verbose = True` then `self.disable = False`. 

5. [x] In the `name` method, the docstring does not adequately explain what the `rank` argument is used for. From looking at the code, it seems that one can choose the rank of the name you want returned, so if you run `name(562, 'genus')` you would get back `'Escherichia'`, where 562 is the taxid for *Escherichia coli*.

6. [x] In several places the script attempts to check whether a taxid argument is an int. An example is shown below, but similar instances are found in `name`, `lineage`, `rank`, `parent`. Another functions, `is_common_ancestor` and `get_lineage_dataframe`, does not have any type checking. Briefly, what is currently being done is that we try to cast the `taxid` argument as an `int`, and if there is a ValueError, then a log message is displayed and we return `None` or something. The problem here is that there will be no error if you cast a float as an int. What is more, the rounding in this case is also weird, so for example `12.9` would become `12` when cast as an int. I would suggest that since this check is done a few different times that a new function is made (perhaps called `is_valid_taxid`), that first checks that the input is an int and secondly that it is included in nodes.dmp or merged.dmp. Probably the best way of doing the type check is as follows:

```python
# Note you will have to insert code to check whether the taxid is in nodes.dmp or merged.dmp
if isinstance(taxid, int):
    return True
elif isinstance(taxid, float):
    return taxid.isinteger() # This checks if it is something like 12.0 vs. 12.9
else
    return False
```

Problem lines (example):
https://github.com/KwanLab/Autometa/blob/43b67d90cc5cc56c02c273ac453611f7698506ea/autometa/taxonomy/ncbi.py#L114-L118

7. [x] In the `name` method, if the `taxid` argument is `1`, then a return statement will never be encountered in the while loop:

https://github.com/KwanLab/Autometa/blob/43b67d90cc5cc56c02c273ac453611f7698506ea/autometa/taxonomy/ncbi.py#L125-L129

8. [x] This is a minor thing, but in the docstring of `lineage`, there is a quote mark missing in the line that specifies the structure of the output list.

https://github.com/KwanLab/Autometa/blob/43b67d90cc5cc56c02c273ac453611f7698506ea/autometa/taxonomy/ncbi.py#L139-L142

9. [x] In the method `get_lineage_dataframe` there is a temporary dictionary constructed called `taxids_`, while there is also a list used called `taxids`. I think the name `taxids_` is a little confusing here and should probably be changed?

10. [x] In the `rank` method the docstring does not include a description of what the function does. From looking at the code, it is a fairly simple function that takes a taxid and returns its rank. Note: There is a comment that says that if the taxid is not found in nodes.dmp, then 'unclassified' is returned (there is also a similar comment in the `parent` method). This would be better to put in the docstring so that it will appear in the documentation. Another point is do we want to also make this function check merged.dmp?

11. [x] The docstring of the `parse_names` method does not state what the function does. From looking at the code it returns a dictionary that holds taxid keys and values are the taxid names. Another issue is that two arguments are mentioned in the docstring when the function does not take arguments. What the docstring means is that class instance variables are used as these arguments, and so would be more correctly shown as `self.names_fpath` and `self.verbose`. This also applies to `parse_nodes`. 

12. [x] In the `parse_names` method the definition of the variable `is_scientific` is superfluous, and two statements could be combined in the if statement:

https://github.com/KwanLab/Autometa/blob/43b67d90cc5cc56c02c273ac453611f7698506ea/autometa/taxonomy/ncbi.py#L283-L285

13. [x] The docstring for the `parse_merged` method is wrong, in that the return structure seems to be pasted from the `parse_nodes` method. In reality it returns a `merged` dictionary in the form `{old_taxid: new_taxid}`. 

14. [x] The code in the `is_common_ancestor` seems to be incorrect. The stated aim of the function is to determine whether the two provided taxids (`parent_taxid` and `child_taxid`) have a non-root common ancestor. How it does this is to go through all the ancestors of `child_taxid` until one of them is equal to `parent_taxid`. However, let's take the case where `parent_taxid` is *Escherichia coli* (taxid 562) and `child_taxid` is Enterobacterales (taxid 91347). These two taxids share a common ancestor (Enterobacterales and ancestors thereof), but the `child_taxid` will never be equal to `parent_taxid` during the running of the method, and therefore it will incorrectly return `False`. The absolute need for one argument to be further up the tree than the other is unnecessary, and not suggested by the function name. A better way would be to make sets from the lineage of each taxid and do an intersection operation (after taking out root).

**Comment by jason-c-kwan** [comment]
Hey @WiscEvan - even if you don't do this one I think you might need to comment in case I have misinterpreted the intention of any part of this.

**Comment by Sidduppal** [comment]
@WiscEvan I was thinking of taking up this issue, as per the above comment let me know in case some comment is misinterpreted or not :smile:

**Comment by WiscEvan** [comment]
> @WiscEvan I was thinking of taking up this issue, as per the above comment let me know in case some comments in the issue are misinterpreted or not 😄

Go for it! 👍 

I'm happy to chime in where needed. I'll place some comments respective to Jason's in this issue as well

**Comment by WiscEvan** [comment]
>4. In the __init__ method, I am wondering if the self.disable variable is needed or ever used? It seems to be defined as not self.verbose, meaning that if self.verbose = True then self.disable = False.

`self.disable` is set for the `tqdm` module so we do not have to continually write `not self.verbose` within the `tqdm` function.

**Comment by WiscEvan** [comment]
> 2. At the top of the script a few constants are defined, BASE_DIR, which is the folder that contains the autometa folder, and NCBI_DIR which is defined as BASE_DIR/databases/ncbi. I just wanted to check if this is intended? I think I saw somewhere else that the default database directory is supposed to be INSIDE the autometa folder, rather than at the same level?

* `BASE_DIR` should refer to `~/Autometa/autometa`
* `NCBI_DIR` should be `~/Autometa/autometa/databases/ncbi`
* This translates to `BASE_DIR/databases/ncbi`.

Note, previously this was:
* `BASE_DIR` : `~/Autometa/`
* `NCBI_DIR` : `~/Autometa/databases/ncbi`
