### ISSUE TITLE
[Dev branch] Issues with autometa/common/external/diamond.py

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#36]
This file contains functions and the DiamondResult class used to running and processing Diamond blast results. Here are the issues that I noticed during code review.

1. [x] In the script, there is an argument/variable called `top_pct` or a variant of this name. This is a float value between 0 and 1 (although it can't exactly be zero), used to determine if the bitscore of hits is above a threshold. For example, if it is 0.9 then only bitscores >= 0.9 * the top bitscore are accepted. The problem here is not one of programmatic logic, but rather readability for contributors. `top_pct` looks like "top percentage", which would suggest, for example, that for a value of 0.9, 90% will be kept. However, the opposite is true in this case - only 10% will be kept. This is compounded by the help message in the `if __name__ == '__main__':` block, which describes this argument as "top percentage of hits to retrieve". So what I am saying is that the variable name and documentation is confusing. Perhaps it could be called "bitscore_tolerance" or something? Accompanied by a change in documentation and inclusion of explanatory comments.

2. [x] `makedatabase` function. I believe that database processing can be parallelized in Diamond, so it doesn't make sense here to have the default number of processors `1`. (Note: the `blast` function seems to have a default cpu value of zero, so you should double check whether Diamond interprets this as using all available cpus). This function also does not have a docstring.

3. [x]  `blast` function. This function carries out an actual Diamond blast search, and one of its arguments is `blast_type`, which is supposed to only have the values `blastp` or `blastx` (which I think are the only ones that Diamond can do). However, later on when the command is being constructed, `blastp` is hardcoded. So This should be changed to allow the function's `blast_type` argument to be used.

https://github.com/KwanLab/Autometa/blob/59941204e1ebb59a04da01b9bbd46c7fd50d3e7b/autometa/common/external/diamond.py#L192-L210

4. [ ] In the function `add_taxids` the docstring mentions that there is a todo task to make this function handle instances where taxids found in the prot.accession2taxid.gz file are not present in the nodes.dmp file (for instance by checking the merged.dmp file). This could be tackled if you would like to do it, and would probably require the involvement of the NCBI class. However, the main thing here is that the docstring should probably tell us that at present there is no handling of this, and taxids might be returned as `None` if there is a problem.

5. [x] The `add_taxids` function allows the accessing of either an uncompressed prot.accession2taxid file or the gzipped prot.accession2taxid.gz version. When the filehandle is opened, there is a choice depending on the filename:

https://github.com/KwanLab/Autometa/blob/59941204e1ebb59a04da01b9bbd46c7fd50d3e7b/autometa/common/external/diamond.py#L347

Then later, we have to invoke another variable called `is_gzipped` so that we know what to do with each line later (`line.decode()` or just `line`):

https://github.com/KwanLab/Autometa/blob/59941204e1ebb59a04da01b9bbd46c7fd50d3e7b/autometa/common/external/diamond.py#L351-L363

This is a matter of style/simplification, but you don't need the `is_gzipped` business. Instead, you can just choose to open the gzipped file using `'rb'` mode, like this: `gzip.open('file.gz', 'rb')`, then use it like a normal filehandle.

6. [x] The `DiamondResult` docstring is not great. It should explain what the class is, what it does, and how it is used. Also, none of the component methods of the class have any docstrings.

**Comment by kaw97** [comment]
In terms of issue 1, would it be possible to rename the variable? Top_pct sounds like it could be more accurately described as "bottom percentile" or some derivative thereof.

E.g. if you score in the 90th percentile on a standardized test, you scored better than 90% of test-takers.

**Comment by jason-c-kwan** [comment]
Yes, you could do that, but just make sure that the new name is logical and makes the code more readable. The primary aim is to reduce the chance of someone coming along in 5 years and messing it up because they didn't quite understand what was going on. (BTW sometimes that person is yourself, having forgotten what the code you wrote is supposed to do - which is why readability is important).

**Comment by WiscEvan** [comment]
An example of [4] is in the `lca.py` section.

The merged dictionary from NCBI is inherited in the LCA class. LCA is parsing taxids from the blast results and if `None` is encountered then the taxid is searched in the merge dict to see if this has been deprecated/suppressed/removed. 

(Line 293 is replacing deprecated taxids) For reference:
https://github.com/KwanLab/Autometa/blob/59941204e1ebb59a04da01b9bbd46c7fd50d3e7b/autometa/taxonomy/lca.py#L287-L293
