### ISSUE TITLE
Jason has not yet finished the code review

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#39]
The issue is that @jason-c-kwan has not yet finished the code review, and his progress has also been rather slow. To help others contribute to the code review, the following is a list of files that are either completed or in progress. Issues are mentioned where one was created, so if there is something with a check mark and no issue, it is probably OK. If you are reviewing something, perhaps leave a comment.

Key:
👀 - in progress
✔️ - done
⭐ - currently being looked at

* `autometa.py` ✔️ 
* `autometa/__main__.py` ✔️  issue #60 
* `autometa/binning/recursive_dbscan.py` ✔️  issue #52  
* `autometa/common/coverage.py` ✔️  issue #21 
* `autometa/common/kmers.py` ✔️  issue #17 
* `autometa/common/mag.py` ✔️  issue #53 
* `autometa/common/markers.py` ✔️  issue #44
* `autometa/common/metagenome.py` ✔️ issue #54 
* `autometa/common/utilities.py` ✔️  issue #40 
* `autometa/common/external/bedtools.py` ✔️  issue #18 
* `autometa/common/external/bowtie.py` ✔️  issue #20 
* `autometa/common/external/diamond.py` ✔️  issue #36 
* `autometa/common/external/hmmer.py`  ✔️  issue #43 
* `autometa/common/external/prodigal.py` ✔️  issue #16 
* `autometa/common/external/samtools.py` ✔️  issue #19 
* `autometa/config/__init__.py` ✔️  issue #58 
* `autometa/config/databases.py` ✔️  issue #59 
* `autometa/config/environ.py` ✔️  issue #55 
* `autometa/config/project.py` ✔️  issue #56 
* `autometa/config/user.py` ✔️  issue #57 
* `autometa/taxonomy/lca.py` ✔️  issue #41 
* `autometa/taxonomy/majority_vote.py` ✔️  issue #42 
* `autometa/taxonomy/ncbi.py` ✔️ issue #33

**Comment by jason-c-kwan** [comment]
Can I close this now, or are there other files I need to review?

**Comment by jason-c-kwan** [comment]
OK, seems like there are some extras:

* `autometa/common/exceptions.py`
* `autometa/common/external/work_queue.py`
* `autometa/datasets/__init__.py` <- not much in this one yet.

And there are tons of old scripts in the `validation` folder. 

Which of the above are ready to be reviewed?

**Comment by WiscEvan** [comment]
None of the above are ready to be reviewed at this time
