### ISSUE TITLE
[dev branch] Issues with autometa/common/utilities.py

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#40]
This file contains common utility functions (no classes) used by Autometa scripts. I found the following issues.

1. [x] This script does not follow the template in `docs/template.py`. In particular, there is no way to run any of the functions from the command line.

2. [x] The `gunzip` function is supposed to uncompress a `.gz` file. The problem is that it loads the entire thing into memory, which is not very efficient, and would perhaps fail for very large files. You only need to load a single line at a time, like this:

```python
output_file = open('output_path', 'w')
with gzip.open('input_path', 'rb') as fh:
    for line in fh:
        output_file.write(line)
output_file.close()
```

Note that if you use `gzip.open` in `'rb'` mode, then you don't need `line.decode()`. 

Another thing to note with this function is that it will more than double the space being taken up by the original `'.gz'` file. Perhaps there should be the option to delete the original `'.gz'` file, if the uncompressing finished correctly.

3. [x] The `file_length` function should work correctly, but it will take a very long time for some of the NCBI database files. Essentially what this function is used for is to return the number of lines in a file. Now, that is all well and good, but oftentimes in the pipeline, this is only used to get a figure for use by [tqdm](https://tqdm.github.io/). Tqdm is a module that provides nice looking progress bars for lengthy iterations, but it needs to know ahead of time how many iterations there will be. Why am I bringing this up? Well there are times in the pipeline where we use this function to get that figure, and it will take a long time because it has to go through the entire file. That is all well and good when we really need an accurate value, but when we want it for tqdm it is just for the sake of looking pretty! (In other words, we get a performance hit). So, I would suggest that there be a way to run this in "approximation mode". Sometimes the NCBI files are like tables where the lines vary a bit in length but are basically the same all the way through. One could make an estimate of the average line length, then use the total size of the file to estimate line number (e.g. by working out how much binary space should be taken up by lines of your average length).

4. [x] In the `get_checksum` function, the docstring incorrectly states that a checksum is retrieved for the provided `args`, but the one argument is `fpath`. Another issue is the use of the SHA-256 hashing algorithm here. SHA-1 would be much quicker, especially for very large files. SHA-1 is not used for security any more because it has been cracked. I would argue that in this case we don't need security and it would be better to use a fast hashing algorithm. I believe that SHA-1 is the fastest.

**Comment by WiscEvan** [comment]
> 4. In the get_checksum function, the docstring incorrectly states that a checksum is retrieved for the provided args, but the one argument is fpath. Another issue is the use of the SHA-256 hashing algorithm here. SHA-1 would be much quicker, especially for very large files. SHA-1 is not used for security any more because it has been cracked. I would argue that in this case we don't need security and it would be better to use a fast hashing algorithm. I believe that SHA-1 is the fastest.

This should perhaps be tackled here: #71

**Comment by WiscEvan** [comment]
```shell
md5 -r autometa/databases/ncbi/prot.accession2taxid.gz  12.87s user 1.77s system 112% cpu 13.048 total
(autometa) ➜  Autometa git:(databases) ✗ time shasum autometa/databases/ncbi/prot.accession2taxid.gz
358b458b07fa444a5d923dc8533156c741a6ecbe  autometa/databases/ncbi/prot.accession2taxid.gz
shasum autometa/databases/ncbi/prot.accession2taxid.gz  10.76s user 1.93s system 89% cpu 14.175 total
(autometa) ➜  Autometa git:(databases) ✗ time shasum autometa/databases/ncbi/prot.accession2taxid.gz
358b458b07fa444a5d923dc8533156c741a6ecbe  autometa/databases/ncbi/prot.accession2taxid.gz
shasum autometa/databases/ncbi/prot.accession2taxid.gz  10.64s user 1.42s system 92% cpu 13.047 total
(autometa) ➜  Autometa git:(databases) ✗ time md5sum autometa/databases/ncbi/prot.accession2taxid.gz
7a6e09d7796f2a36d2a844c251255de3 autometa/databases/ncbi/prot.accession2taxid.gz
md5 -r autometa/databases/ncbi/prot.accession2taxid.gz  12.72s user 1.67s system 111% cpu 12.874 total
```

It appears sha1 is faster than md5, however, NCBI has md5 checksums so I've implemented this. I could similarly have an option to specify the algorithm desired.

**Comment by WiscEvan** [comment]
>2. Note that if you use gzip.open in 'rb' mode, then you don't need line.decode().

The default for `gzip.open` is 'rb' mode and this will retrieve a `bytes` string. If you do not use the `decode` method, then you will get a `bytes` object rather than `str` object. 

Example:

```python
In [79]: fh = gzip.open('autometa/databases/ncbi/prot.accession2taxid.gz','rb')

In [80]: for l in fh:
    ...:     break
    ...:

In [81]: l
Out[81]: b'accession\taccession.version\ttaxid\tgi\n'

In [82]: type(l)
Out[82]: bytes

In [83]: l.decode()
Out[83]: 'accession\taccession.version\ttaxid\tgi\n'
```

However, we _can_ open the file in _text_ mode.

```python
In [86]: fh = gzip.open('autometa/databases/ncbi/prot.accession2taxid.gz','rt')

In [87]: for l in fh:
    ...:     break
    ...:

In [88]: l
Out[88]: 'accession\taccession.version\ttaxid\tgi\n'
```

**Comment by WiscEvan** [comment]
>1. This script does not follow the template in docs/template.py. In particular, there is no way to run any of the functions from the command line.

Do we want/need to have this as a standalone module?
