### ISSUE TITLE
[dev branch] Issues with autometa/taxonomy/lca.py

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#41]
This file contains the logic involved in figuring out the lowest common ancestor (LCA) of each predicted ORF in metagenomic contigs. Note, that the logic involved in taking that information and converting it to a taxonomy for each contig is found in `autometa/taxonomy/majority_vote.py`. Also, please be aware that this file contains some complex alorithms involving dynamic programming, as well as advanced concepts such as passing functions around as arguments etc. As such, please don't change anything unless you know what you are doing. I don't think any of the issues below really affect the algorithmic stuff, but you might want to ask @WiscEvan if in doubt. The Issues I found with this file are as follows:

1. [x] The docstring of the file should mention that the file contains the definition of the `LCA` class.

2. [x] The `argparse` help messages could be made to be more helpful to users. For instance, the message for the `orfs` positional argument should specify that an amino acid fasta file is required. Also, it should be stated here that the script expects blast output in the standard `-outfmt 6` format (this information is in the main script docstring, but will not show up on the command line help message).

3. [x] The docstring for the `LCA` class is not very descriptive.

4. [x] The `prepare_tree` method makes data structures that define the Eulerian tour and are used later to make the sparse table. In this method, it would be useful to include links for explanations on what a Eulerian tour is, and why it is useful here, in the docstring. Or, since the documentation now takes directly from comments, a more complete explanation could be offered here.

5. [x] In the `prepare_tree` method, the variables `self.tour_fp`, `self.level_fp` and `self.occurrence_fp` are accessed to determine if they are valid files. These are supposed to be the filenames of pickled datastructures. If they already exist, then they are unpickled, otherwise this method will go ahead and make them. The problem here is that if they exist but are in some way corrupted, then the function does not handle this. I would suggest that the unpickle steps are done in a `try`/`except` block, so that the files can be remade if they are corrupted.

6. [x] The `prepare_tree` method goes through `self.nodes_fpath` (the file path to nodes.dmp) to create some datastructures: `taxids`, `parents`, `children`. However, this is unnecessary because the `LCA` class is inherited from the `NCBI` class, and we already did `super().__init__` in the `__init__` method of this class. What this means is that when initializing an `LCA` object, essentially we also initialize an `NCBI` object first then do some extra stuff to it. During the `NCBI` initialization process, nodes.dmp was already parsed to give us `self.nodes` and other data structures. The nodes file is fairly large, so by pointlessly going through it again here we are wasting time and memory.

7. [x] The `preprocess_minimums` method constructs the sparse table to be used later to lookup LCAs through the range minimum query method. This part uses dynamic programming, which is sort of a fancy way of saying that we make a non-redundant lookup table - i.e. all possible LCAs can easily be read from this thing and we never have to do the same calculation twice. One issue is that the first step involves seeing if `self.sparse_fp` is a path that exists, and if so to unpickle it (otherwise it is recreated). The same criticism as above applies here - there is no error handling for the case where the pickle file exists but is corrupted. That case could easily handled by overwriting the file.

8. [x] This is perhaps a nitpick, but in `preprocess_minimums` the variable `sparse_matrix` is perhaps confusing because it is actually a numpy array. There is another object type called a numpy matrix, but this is deprecated. I'm just thinking that future contributors might be looking up the wrong things in the numpy documentation.

9. [x] In the `preprocess_minimums` method, the variables `lower_index` and `upper_index` are explicitly cast as `ints`. Is this necessary? I am just trying to think of when they would not be ints, and whether rounding might be a problem.

10. [x] In the `preprocess_minimums` method, it would be good to include an explanation of what is going on and why, perhaps in the docstring. Because it is not immediately obvious and takes some reading and thought to understand.

11. [x] There is no docstring for the `prepare_lca` method. 

12. [x] In the `lca` method, there is a check whether either arguments `node1` or `node2` are not in `self.occurrence` (one of the data structures describing the Eulerian tour). If either are not found then a ValueError is raised. My concern here is that this check is actually fairly far down and could allow invalid taxids to be returned. So I would suggest that this check is moved further up, perhaps to just under the check for whether both `node1` and `node2` are `None`.

13. [x] In the `get_lcas` method, there is a part that gets the taxid for a specific sseqid, and then a part that checks whether anything was assigned to `taxid`, and if not we `continue`. Well, as you can see from the code below, we use a `dict.get` statement where we specify a default, so there is no way that `taxid` will be `None`. So the `if not taxid: continue` part can be deleted.

https://github.com/KwanLab/Autometa/blob/59941204e1ebb59a04da01b9bbd46c7fd50d3e7b/autometa/taxonomy/lca.py#L287-L293

14. [x] In the `blast2lca` method, the docstring does not mention the `force` argument.

15. [x] In the `blast2lca` method, there is an argument called `blast`, which is the path to a blast table. During the course of the method, it checks whether this is a path that already exists. If it does, then this is used later by `diamond.parse`. However, if it doesn't exist, then the method actually makes it's own diamond path based on the `fasta` path and then runs diamond:

https://github.com/KwanLab/Autometa/blob/59941204e1ebb59a04da01b9bbd46c7fd50d3e7b/autometa/taxonomy/lca.py#L347-L355

The problem here is that this function can be run, with a specified diamond table path (`blast`), which is then ignored if it doesn't exist, and the diamond output will be written to an unexpected place.

16. [x] In the `write_lcas` method, it takes a dictionary of lcas for each qseqid, and outputs it to `outfpath`. The problem is that it constructs the entire file in memory before writing it out:

https://github.com/KwanLab/Autometa/blob/59941204e1ebb59a04da01b9bbd46c7fd50d3e7b/autometa/taxonomy/lca.py#L384-L392

However, a more memory efficient way would be to write each line one at a time:

```python
outfile = open(outfpath, 'w')
outfile.write('qseqid\tname\trank\tlca\n')
for qseqid, taxid in lcas.items():
    outfile.write('\t'.join(map(str,[qseqid, self.name(taxid), self.rank(taxid), taxid])) + '\n')
outfile.close()
```

17. [x] In the `parse` method, the variable `translations` is defined as:

https://github.com/KwanLab/Autometa/blob/59941204e1ebb59a04da01b9bbd46c7fd50d3e7b/autometa/taxonomy/lca.py#L427

However, the name `translations` is confusing, because what this is is a dictionary that tells us which contig each protein sequence belongs to. So I suggest the variable name is changed.

18. [x] In the `aggregate_lcas` method, the docstring does not explain what the `orfs_lcas` argument should be (in terms of object/data type).

19. [x] I'm not sure if the `aggregate_lcas` method is needed, as it seems to duplicate functionality found in `prodigal.py` which is used by other methods here.

**Comment by WiscEvan** [comment]
> 6. The prepare_tree method goes through self.nodes_fpath (the file path to nodes.dmp) to create some datastructures: taxids, parents, children. However, this is unnecessary because the LCA class is inherited from the NCBI class, and we already did super().__init__ in the __init__ method of this class. What this means is that when initializing an LCA object, essentially we also initialize an NCBI object first then do some extra stuff to it. During the NCBI initialization process, nodes.dmp was already parsed to give us self.nodes and other data structures. The nodes file is fairly large, so by pointlessly going through it again here we are wasting time and memory.

`nodes.dmp` may seem large, but it is rather small compared to most other NCBI database files.

For an idea of the parsing times see below:

```python
from autometa.taxonomy.ncbi import NCBI

ncbi = NCBI('autometa/databases/ncbi')

%timeit ncbi.parse_nodes()
4.19 s ± 38.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit ncbi.parse_names()
3.86 s ± 70.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit ncbi.parse_merged()
67.5 ms ± 505 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Although. I have resolved this in `prepare_tree` so we do not reopen this file.

**Comment by WiscEvan** [comment]
>16. In the write_lcas method, it takes a dictionary of lcas for each qseqid, and outputs it to outfpath. The problem is that it constructs the entire file in memory before writing it out.

I've addressed this in another issue (https://github.com/KwanLab/Autometa/issues/43#issuecomment-626203264). But there are reasons as to why you would not want to repeatedly call the write method. I've placed a routine to buffer the memory used.

**Comment by WiscEvan** [comment]
>9. In the preprocess_minimums method, the variables lower_index and upper_index are explicitly cast as ints. Is this necessary? I am just trying to think of when they would not be ints, and whether rounding might be a problem.

We are navigating between numpy and python, so we must first convert the `numpy.float64` to an `int` for index accession of the levels list (`self.level`).

Otherwise we are attempting to access our list with a float which results in the following error:

```python
~/Autometa/autometa/taxonomy/lca.py in preprocess_minimums(self)
    251                 upper_index = sparse_array[(row + 2**(col-1)), (col-1)]
    252                 # Access levels via comparison indices
--> 253                 lower_min = self.level[lower_index]
    254                 upper_min = self.level[upper_index]
    255                 # Set the winning minimum between the range of indices

TypeError: list indices must be integers or slices, not numpy.float64
```
