### ISSUE TITLE
[dev branch] Issued with autometa/taxonomy/majority_vote.py

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#42]
This file contains the functions which carry out the majority vote algorithm (basically this takes the lowest common ancestor/LCA information for each ORF from each contig, and converts this information into a single taxid for each contig). The algorithm is the same as in Autometa 1.0, and I didn't find any problems with the actual logic of it. Other issues with the script are outlined below:

1. [x] The docstring of `majority_vote` is not very descriptive for all the arguments.

2. [x] In the `majority_vote` function, we call the `lca` and `voted_taxids` functions, and use `dict.get` expressions to bring up relevant arguments. However, in the `lca` call, the default for `verbose` is `True`, whereas in the `voted_taxids` call, the default for `verbose` is `False`. These should both probably match the command line default for `verbose`, which is `False`.

https://github.com/KwanLab/Autometa/blob/59941204e1ebb59a04da01b9bbd46c7fd50d3e7b/autometa/taxonomy/majority_vote.py#L266-L272

https://github.com/KwanLab/Autometa/blob/59941204e1ebb59a04da01b9bbd46c7fd50d3e7b/autometa/taxonomy/majority_vote.py#L287-L291

3. [x] In the `rank_taxids` function, the docstring is not very descriptive about what sort of data structure the argument `ctg_lcas` should be.

4. [x] In the `rank_taxids` function, we initialize an `NCBI` object in order to access various aspects of the taxonomy tree. However, `rank_taxids` is called by `majority_vote`, and in the latter function, we already created an `LCA` object. Because the `LCA` class inherits from `NCBI`, the initialization of each involves parsing through the entire NCBI taxonomy and storing it in memory. So, as written currently we are wasting time and memory unnecessarily (i.e. we parse the NCBI taxonomy twice into two separate copies in memory). It would be more efficient to pass the `LCA` object to `rank_taxids`. Other functions in the script expect an NCBI object, and would be fine with the LCA object instead.

5. [x] In the function `is_consistent_with_other_orfs`, the docstring appears to be wrong. It states that the `ctg_lcas` argument is a dictionary in the form `{ctg1:{canonical_rank:{taxid:num_hits,...},...}, ctg2:{...},...}`, when the function actually expects a dictionary for a single contig, so `{canonical_rank:{taxid:num_hits,...}, canonical_rank:{...},...}`. The docstring should also make clear, since a the same variable name is used elsewhere in a different context, that this argument is a dictionary for a single contig.

6. [x] In the function `lowest_majority`, the docstring does not include a description of what the function does. This will be important as the docs take function descriptions directly from the code comments. The docstring should also make clear that the `ctg_lgas` argument is for a single contig (see comment 5).

7. [x] In the `write_votes` function, the docstring mentions a ResultsNotFoundError, but that part of the main code has been commented out. So this part should be removed from the docstring as it is not current.

8. [x] The `write_votes` function writes a file to disk which is basically a table of contigs and their taxids determined by the script, copied from the dictionary `results`. The problem is that as written currently, the function makes a variable called `outlines`, which stores the entire contents of this file before writing it out. This is an unnecessary waste of memory. Instead, the file could be written line by line, like this:

```python
if os.path.exists(outfpath):
    raise FileExistsError(outfpath)
output = open(outfpath, 'w')
output.write('contig\ttaxid\n')
for contig,taxid in results.items():
    output.write(f'{contig}\t{taxid}\n')
output.close()
return outfpath
```

**Comment by WiscEvan** [comment]
> 8. The write_votes function writes a file to disk which is basically a table of contigs and their taxids determined by the script, copied from the dictionary results. The problem is that as written currently, the function makes a variable called outlines, which stores the entire contents of this file before writing it out. This is an unnecessary waste of memory. Instead, the file could be written line by line, like this:

```python
In [1]: def write_large_file_one_write(text,n_lines):
    ...:     lines = '\n'.join(text for _ in range(n_lines))
    ...:     fh = open('test.txt','w')
    ...:     fh.write(lines)
    ...:     fh.close()
    ...:     return
    ...:

In [2]: def write_large_file(text,n_lines):
    ...:     lines = (text for _ in range(n_lines))
    ...:     fh = open('test.txt','w')
    ...:     for line in lines:
    ...:         fh.write(f'{line}\n')
    ...:     fh.close()
    ...:     return
    ...:

In [3]: text = 'WEARETHEKNIGHTSWHOSAYNI!'

In [4]: n_lines = 10000000

In [5]: %timeit -n10 write_large_file(text, n_lines)
2.91 s ± 59.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [6]: %timeit -n10 write_large_file_one_write(text, n_lines)
1.03 s ± 8.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

```

This is just to make the point, there are performance improvements to balance with memory usage. As shown from calling the `write` method once, versus for every line.
