### ISSUE TITLE
create autometa conda recipe

### ISSUE THREAD

**Issue by WiscEvan** [KwanLab/Autometa#5]
Write a conda recipe to allow users to install autometa and its dependencies with the simple command:

 `conda install -c bioconda autometa`

Note, this command assumes the autometa conda recipe is housed in the [_bioconda_](https://bioconda.github.io/) channel.

Conda recipes tutorial - [link](https://python-packaging-tutorial.readthedocs.io/en/latest/conda.html "python-packaging-tutorial")

closed Autometa-2.0.0a PR - https://github.com/bioconda/bioconda-recipes/pull/21480

**Comment by chasemc** [comment]
nf-core linter expects a `environment.yml`. While we can turn off that lint check I think it may be beneficial to consider switching from `requirements.txt` to `environment.yml`
![image](https://user-images.githubusercontent.com/18691127/122279212-6b4ffb80-cead-11eb-80bb-1f05d77e1029.png)

**Comment by WiscEvan** [comment]
Hosted https://anaconda.org/bioconda/autometa
