### ISSUE TITLE
[dev branch] Issues with autometa/binning/recursive_dbscan.py

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#52]
I hope it is OK to not use one of the issue templates, but I couldn't see "code review" there. This script contains functions required for clustering contigs and recursively searching for bins with the highest completeness and purity. I noticed the following issues as part of my code review.

1. [x] In the `recursive_dbscan` function, during each iteration the uses a different value for `eps`, we calculate the median completeness of the bins that pass the completeness and purity cutoffs. As stated in the NAR article, the `eps` value which gives the greatest median completeness is considered the best. The code that calculates the median is shown below:

https://github.com/KwanLab/Autometa/blob/3e8c7718dc63e5a06654a899506535ae8bd6219e/autometa/binning/recursive_dbscan.py#L103

However, the problem here is that the dataframe `df` has rows for each contig, and a column for 'completeness' (i.e. each contig in a particular cluster will have the same value for completeness under this column heading). So, what that means is that the above code will take a completeness value for each contig, and calculate the median from that. This is not what is intended - in the last version what was done was a completeness value for each individual cluster was used to calculate median. The way it is done above, there will be biases depending on the number of contigs a cluster has. I would suggest something like the following:

```python
import statistics
cluster_completeness = dict() # Keyed by cluster
clusters = dict(list(df.groupby('cluster'))).keys()
for index, row in df.iterrows():
    cluster = row['cluster']
    if cluster in cluster_completeness:
        continue
    else:
        completeness = row['completeness']
        cluster_completeness[cluster] = completeness   
median_completeness = statistics.median(list(cluster_completeness.values()))
```
Note: I am not a Pandas expert, so there could be a better way of doing the above.

2. [x] In the `run_dbscan` function, there is no description of the `df` and `eps` arguments in the docstring.

3. [x] In the `run_dbscan` function, there is an initial check to see of `n_samples` (i.e. the number of rows) is 1. If it is, then it is kind of pointless to do clustering on it, and it looks like the intended behavior is that the cluster for the one contig be recorded as `pd.NA`, before the dataframe is returned:

https://github.com/KwanLab/Autometa/blob/3e8c7718dc63e5a06654a899506535ae8bd6219e/autometa/binning/recursive_dbscan.py#L172-L177

There is a potential problem here - immediately after this check we drop some columns from the dataframe, which by default are `['cluster', 'purity', 'completeness']`. I think that this drop columns part should be before the 1 row check, because the returned 1 row dataframe might have old cluster, purity and completeness values which will be left there (I actually don't know what will happen during the merge statement if there is already a column called 'cluster').

4. [x] There is a bit of confusion in the `run_dbscan` function about the embedded dimensions. In the def line, it says that the default value of `usecols` is `['x', 'y']` (i.e. DBSCAN on two embedded dimensions, excluding coverage). However, in the docstring, it says that the default is `['x', 'y', 'coverage']` if `coverage` is present in the dataframe, otherwise it is `['x', 'y', 'z']`. Leaving aside the problem that we aren't given the option of using three embedded dimensions without coverage, it turns out that in the function body `usecols` is never used. Instead, we first add `['x', 'y']` to `cols`, then if `coverage` is in the dataframe we use that, otherwise we add `z`. One problem with this behavior, is if `coverage` is not present in the table, then it doesn't check whether `z` is there, so there may be an error in that circumstance. I would suggest that we implement the default behavior outlined in the docstring properly, but have a check that `z` exists. Perhaps there should also be an option in case the user wants to just use `x` and `y`.

5. [x] In the `add_metrics` function, there is no description of the argument `df` in the docstring.

6. [x] In the `add_metrics` function, there is a `domain` argument which tells the function how many markers to expect in a cluster. We translate this to an expected total like this:

https://github.com/KwanLab/Autometa/blob/ddc2bf951d6c4a8c29e9e2301e15a762327b0267/autometa/binning/recursive_dbscan.py#L213-L214

The `dict.get` method here searches for the `domain` in `marker_sets`, and if it doesn't find the key then it returns `139`. Instead, there should probably be an error thrown with a message saying that the domain is not recognized. This should aid troubleshooting (for example - a script could contain archaea misspelled or something).

7. [x] In the `binning` function, if the `master` dataframe doesn't have any marker information in it, then we throw a `RecursiveDBSCANError`. Since we have also implemented HDBSCAN it should probably be something like `RecursiveBinningError`. Come to think of it, the script name `recursive_dbscan.py` is also a bit specific.

**Comment by WiscEvan** [comment]
>1.n the recursive_dbscan function, during each iteration the uses a different value for eps, we calculate the median completeness of the bins that pass the completeness and purity cutoffs. As stated in the NAR article, the eps value which gives the greatest median completeness is considered the best.  `median_completeness = df[completess_filter & purity_filter]['completeness'].median()`

> However, the problem here is that the dataframe df has rows for each contig, and a column for 'completeness' (i.e. each contig in a particular cluster will have the same value for completeness under this column heading). So, what that means is that the above code will take a completeness value for each contig, and calculate the median from that. This is not what is intended - in the last version what was done was a completeness value for each individual cluster was used to calculate median. The way it is done above, there will be biases depending on the number of contigs a cluster has. I would suggest something like the following:

Typically iterating row by row causes a significant reduction in performance. I've referenced a nice post showing a [few optimization methods for pandas](https://engineering.upside.com/a-beginners-guide-to-optimizing-pandas-code-for-speed-c09ef2c6a4d6)

This is a nice catch. We can use the `groupby` method here to easily resolve this.

 `median_completeness = df[completess_filter & purity_filter].groupby('cluster')['completeness'].median().median()`

Note, this will group our dataframe by cluster then compute the median cluster-by-cluster. The first median call will just be the value as all of the contigs' completeness value in the cluster's grouping will be the same. Then we call median again after all of the clusters' completeness values have been retrieved to get the median amongst all of the recovered clusters that are above the thresholds.

**Comment by WiscEvan** [comment]
>3. In the run_dbscan function, there is an initial check to see of n_samples (i.e. the number of rows) is 1. If it is, then it is kind of pointless to do clustering on it, and it looks like the intended behavior is that the cluster for the one contig be recorded as pd.NA, before the dataframe is returned.

> There is a potential problem here - immediately after this check we drop some columns from the dataframe, which by default are ['cluster', 'purity', 'completeness']. I think that this drop columns part should be before the 1 row check, because the returned 1 row dataframe might have old cluster, purity and completeness values which will be left there (I actually don't know what will happen during the merge statement if there is already a column called 'cluster').

The default behavior is there is a collision in a column name is to append an x and y according to the left or right dataframe respectively. You can also supply values to the `suffixes` argument to append the provided value if a collision occurs. See [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html) for details.

From `pd.merge?`

```python
Examples
--------

>>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [1, 2, 3, 5]})
>>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [5, 6, 7, 8]})
>>> df1
    lkey value
0   foo      1
1   bar      2
2   baz      3
3   foo      5
>>> df2
    rkey value
0   foo      5
1   bar      6
2   baz      7
3   foo      8

Merge df1 and df2 on the lkey and rkey columns. The value columns have
the default suffixes, _x and _y, appended.

>>> df1.merge(df2, left_on='lkey', right_on='rkey')
  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  foo        5  foo        5
3  foo        5  foo        8
4  bar        2  bar        6
5  baz        3  baz        7

Merge DataFrames df1 and df2 with specified left and right suffixes
appended to any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey',
...           suffixes=('_left', '_right'))
  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  foo           5  foo            5
3  foo           5  foo            8
4  bar           2  bar            6
5  baz           3  baz            7
```

**Comment by WiscEvan** [comment]
> 6. In the `add_metrics` function, there is a `domain` argument which tells the function how many markers to expect in a cluster. We translate this to an expected total like this:

> https://github.com/KwanLab/Autometa/blob/3e8c7718dc63e5a06654a899506535ae8bd6219e/autometa/binning/recursive_dbscan.py#L172-L177

> The `dict.get` method here searches for the `domain` in `marker_sets`, and if it doesn't find the key then it returns `139`. Instead, there should probably be an error thrown with a message saying that the domain is not recognized. This should aid troubleshooting (for example - a script could contain archaea misspelled or something).

Can you update the lines you are providing. I do not think you intended to paste these lines? They do not appear to correspond to your comments.

**Comment by WiscEvan** [comment]
> > 1.n the recursive_dbscan function, during each iteration the uses a different value for eps, we calculate the median completeness of the bins that pass the completeness and purity cutoffs. As stated in the NAR article, the eps value which gives the greatest median completeness is considered the best.  `median_completeness = df[completess_filter & purity_filter]['completeness'].median()`
> 
> > However, the problem here is that the dataframe df has rows for each contig, and a column for 'completeness' (i.e. each contig in a particular cluster will have the same value for completeness under this column heading). So, what that means is that the above code will take a completeness value for each contig, and calculate the median from that. This is not what is intended - in the last version what was done was a completeness value for each individual cluster was used to calculate median. The way it is done above, there will be biases depending on the number of contigs a cluster has. I would suggest something like the following:
> 
> Typically iterating row by row causes a significant reduction in performance. I've referenced a nice post showing a [few optimization methods for pandas](https://engineering.upside.com/a-beginners-guide-to-optimizing-pandas-code-for-speed-c09ef2c6a4d6)
> 
> This is a nice catch. We can use the `groupby` method here to easily resolve this.
> 
> `median_completeness = df[completess_filter & purity_filter].groupby('cluster')['completeness'].median().median()`
> 
> Note, this will group our dataframe by cluster then compute the median cluster-by-cluster. The first median call will just be the value as all of the contigs' completeness value in the cluster's grouping will be the same. Then we call median again after all of the clusters' completeness values have been retrieved to get the median amongst all of the recovered clusters that are above the thresholds.
> 
> Although I will admit, this does not appear to be the most elegant solution

In `add_metrics` we are already calculating these values.. So now I'm returning the dataframe containing the clusters with their metrics as well for easy lookup rather than having to group the clusters twice. Which is rather expensive

**Comment by jason-c-kwan** [comment]
I have updated the code snippet in point 6
