### ISSUE TITLE
[dev branch] Issues with autometa/config/databases.py

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#59]
This file contains configuration handling for Autometa databases. Here are the issues I noticed:

1. [x] The main docstring should note that the file contains the definition of the `Databases` class.

2. [x] The `Databases` class does not really have a docstring.

3. [x] There is no docstring for the `satisfied` property of the `Databases` class.

4. [x] In the docstring of the `prepare_sections` method, it would be useful if it explicitly says that `self.config` is amended, like in other method docstrings in this file. **(This function has now been removed and the routine moved to the `__init__`)**

5. [x] The `format_nr` method calls `diamond.makedatabase` to convert `nr.gz` into `nr.dmnd`. Currently `diamond.makedatabase` does not create a checksum file for the dmnd file after that task is completed successfully. That logic could probably be inserted into `format_nr`, so that later we can tell that the diamond database creation finished successfully and we can tell if the file became corrupted since then.

6. [x] In the `extract_taxdump` method, the `untar` function from `utilities.py` is called to extract individual files from `taxdump.tar.gz`. This function doesn't create a checksum file, so it would be good to insert that in `extract_taxdump`. This is so that later it can be checked that the various `.dmp` files are still OK. (NCBI I think supplies a checksum file for taxdump, but not the individual .dmp files as far as I know).

7. [x] In the `update_ncbi` method, the docstring does not specify what type of object the method expects the argument `options` to be. This would be useful for the documentation. **(`update_ncbi` has been removed and functionality is placed in `download_ncbi_files`)**

8. [x] In the `update_ncbi` method, URLs for downloading files from NCBI are taken from `DEFAULT_CONFIG` (i.e. whatever is in the user supplied config file is ignored). I think this is bad because a user might reasonably expect that changes in their config file to be reflected in behavior. There are legitimate reasons to do this as well - for example perhaps they need to use a NCBI FTP mirror website if do not have a fast connection to the main NCBI FTP site or if it is down for whatever reason. **(`update_ncbi` has been removed and functionality is placed in `download_ncbi_files`)**

9. [x] In the `update_ncbi` method, files are only downloaded if it is found that they don't already exist. Apart from the fact that we haven't checked that existing files are still OK (see other comments), or that the files on the NCBI FTP site are newer, since 'update' is in the name of the method, a user might reasonably expect that existing files will be updated/overwritten. **(`update_ncbi` has been removed and functionality is placed in `download_ncbi_files`)**

10. [x] In the `update_markers` method, the docstring does not explicitly state what type of object it expects the argument `options` to be. **(`update_markers` has been removed and functionality is placed in `download_markers`.)**

11. [x] The `update_markers` method also has the same problem as `update_ncbi`, in that it takes URLs from `DEFAULT_CONFIG` and ignores user config files. There are legitimate research reasons that a user might want to supply their own set of marker hmms. We could also include checksum files in the git repo so that it can be checked whether the files downloaded without corruption (as sometimes happens). **(`update_markers` has been removed and functionality is placed in `download_markers`.)**

12. [x] In the `get_missing` method, the wording in the docstring is a little misleading. A user might read the description and expect the method to download files, when actually all it does is return information about what is missing. Note: There is a TODO comment saying that checkpoint validation could be done here, which ties into some of my other comments.

**Comment by WiscEvan** [comment]
>7. In the update_ncbi method, the docstring does not specify what type of object the method expects the argument options to be. This would be useful for the documentation.

The options object is a `set`
