### ISSUE TITLE
[dev branch] Issues with autometa/__main__.py

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#60]
This is the main script to run Autometa. Here are the issues I encountered:

1. In the `init_logger` function, the docstring states that the default is `logging.DEBUG`, but in the def line the default is `logging.INFO`. Then the last line of the function sets the level to `logging.DEBUG` (i.e. ignores the argument).

2. It would be a good idea to include a docstring for the `entrypoint` function at least to explain why it is needed. As far as I am aware this is something to do with bioconda?

**Comment by WiscEvan** [comment]
So, this may appear to be hardcoding the DEBUG level in, but this is placing multiple handlers within the logger object. The Docstring is just a bit off where:

>By default will initialize streaming logger with DEBUG level messages.
    If `fpath` is provided, will write DEBUG level messages to `fpath` and
    set streaming messages to INFO.

Should be

>By default will initialize streaming logger with INFO level messages.
    If `fpath` is provided, will write DEBUG level messages to `fpath` and
    set streaming messages to INFO.

This is hardcoding the written log to contain debug level information so when users are returning to their log, it will have all of the information from their run, while only streaming info level information. This will also be useful, when a user provides a log file. They can specify just `--log` without having to specify `--debug` for them to get the details from their run.

I can change this so their log also just emits whatever level, they provide, but I thought if the user really wants to write a log, they will be able to have all of the details of their run there.

**Comment by jason-c-kwan** [comment]
Thanks for explaining - I agree with this logic.
