### ISSUE TITLE
Zoom behaves weirdly if I change axes while zoomed in

### ISSUE THREAD

**Issue by chanana** [KwanLab/Autometa#79]
## Current Behavior

While visualizing an uploaded tsv file, if I zoom into an area, change the axes, and then try to zoom in/out again, zoom behaves "weirdly". 

## Expected Behavior

It shouldn't behave weirdly.

**Comment by chanana** [comment]
**Description** This is a known bug in the UX. From the looks of it, if you zoom in and change the axes, the animation resets the zoom first and then changes the axes. If you then try to zoom in/out, it starts the animation from the state the graph was in before changing the axes.

**Best guess:** The current implementation of zoom and axes change does not transfer the d3.zoom "state" from the `changeX/Y` functions to the `zoomReset` function. 

**Excuse:** This bug is a result of the lack of knowledge on part of the devs. We're trying to do our best, please have patience.

**Suggested workaround:** Press the reset zoom button once after changing the axes.

**Comment by jason-c-kwan** [comment]
Can you hold the zoom setting in a variable and then add a zoom adjustment part to whatever function does the changing axes?

**Comment by WiscEvan** [comment]
@chanana Is this resolved? If so, can we close this issue?

**Comment by chanana** [comment]
I've referenced it in my commit as "Fix Kwanlab#79" (seen in blue) so if/when I merge my branch, it should close?
