### ISSUE TITLE
Autometa Results Output Format

### ISSUE THREAD

**Issue by chanana** [KwanLab/Autometa#80]
**What I'd like:** Please fill blank values in the tsv output with appropriate values. Importantly, use values that make sense and won't skew the results. 

**Example with reasoning (if possible):** If the minimum value of a column is say `13` and the max is `39`, then filling the blanks with 0 would extend the range of the column by 50%! 

```python
prev_range = 39 - 13 #26
new_range = 39 - 0 #39
increase = new_range / prev_range #1.5
```

If this column was being used for the radius of the circles, the circles will all look very big because of the skew.

**Comment by WiscEvan** [comment]
Can you provide a few more details for context?

My current thinking right now is: I'm not completely sure, but is this in reference to doing some sort of interpolation to coordinate the radii of the circles based on a given column? 

Just a quick search, maybe [this](https://nelsonslog.wordpress.com/2011/04/11/d3-scales-and-interpolation/ "d3 scales and interpolation blog post") can provide some answers?

**Comment by chanana** [comment]
In the `master.tsv` table that I'm working off of, there are columns of data. Some of these columns are numeric others have text values. In the `completeness` and `purity` columns, there are blanks i.e. there is no value there. Similarly in the `cluster` column, there are blanks. I manually put a 0 for the `completeness` and `purity` columns and `unassigned` for the blanks in the `cluster` column. The feature request is to add appropriate blank values for each column instead of just leaving the column <blank>.

![screenshot showing the three columns mentioned](https://user-images.githubusercontent.com/15051933/81973823-50e08a00-95ea-11ea-91f0-d457d90dcd03.png)
Here is a screen shot with the three columns I mentioned.

![screenshot of manually entered "unassigned" value](https://user-images.githubusercontent.com/15051933/81973902-7077b280-95ea-11ea-9700-aae7af441d45.png)
Here is a screenshot of manually entered "unassigned" value in the `cluster` column.

The additional advice I had for the blank values was to make sure to make them near the range to avoid skewing results but perhaps that can be a separate discussion.

**Comment by WiscEvan** [comment]
Previously we have assigned any contig that is unclustered as `unclustered`, would you prefer we write these out in the results? Similarly, the completeness and purity values for unclustered contigs should be `N/A` rather than `0` so as to avoid confusing a contig that _has_ been clustered but has a `purity` or `completeness` that is indeed `0`.

**Comment by chanana** [comment]
> Previously we have assigned any contig that is unclustered as `unclustered`, would you prefer we write these out in the results? 

Yes please.

> Similarly, the completeness and purity values for unclustered contigs should be `N/A` rather than `0` so as to avoid confusing a contig that _has_ been clustered but has a `purity` or `completeness` that is indeed `0`.

`N/A` might cause issues parsing it as a floating point value. Perhaps adding a -1 might be an option?

Alternatively, I can parse `completeness` and `purity` as categorical variables but only if there are a fixed number of possibilities for that column i.e. if completeness is one of 22 values in that column, then a categorical variable might make more sense?

**Comment by WiscEvan** [comment]
This also relates to Autometa's binning outputs. 

See:

* Recursive DBSCAN issue-#52 
* Decision Tree Classifier issue-#61

**Comment by jason-c-kwan** [comment]
Does the current output allow us to calculate the completeness and purity for an arbitrary group of contigs? That would be needed to get the same behavior as Evan's prototype.

**Comment by WiscEvan** [comment]
The marker frequencies are currently in a separate table to reduce redundancy. This can be merged into a final results table if necessary.

**Comment by WiscEvan** [comment]
> Does the current output allow us to calculate the completeness and purity for an arbitrary group of contigs? That would be needed to get the same behavior as Evan's prototype.

You can retrieve completeness and purity in a few lines using only the {domain}.markers.tsv file.

```python
from autometa.common.markers import Markers

# First load the markers table as a pandas DataFrame
df = Markers.load(fpath="bacteria.markers.tsv", format="wide")

# arbitrary markers here that exist within the provided table above
contigs = ["contig_1", "contig_2", "contig_2"]

# Now retrieve the marker counts of the contigs
num_markers_expected = df.shape[1] # markers are columns

# Using the contigs subset, sum the counts of markers
marker_counts = df.loc[contigs].sum()

# We can determine all of the markers that occur at least once
num_unique_markers = markers_counts[marker_counts >= 1].count()

# With the marker sums we can find markers that occur as a single-copy
num_single_copy_markers = markers_counts[marker_counts == 1].count()

# With these counts we can calculate the percent complete/pure
completeness = num_unique_markers / num_markers_expected * 100
purity = num_single_copy_markers / num_unique_markers * 100
```

We could merge the markers table with the binning results as well as the annotations used for binning. I think it may be a bit easier to read to keep them separate. We could try keeping the tables separate then adding the marker annotations when they become available on the back-end? I think this will be a matter of preference from the end-user or @chanana?
