### ISSUE TITLE
Quantifying abundance

### ISSUE THREAD

**Issue by proteinosome** [KwanLab/Autometa#85]
Hi, thanks for making the software. I've been trying this out on a set of contigs assembled using long reads data and it's able to successfully extract a set of species that I expect from the mixture.

A question I have is that is there a way to quantify the abundance of the contigs? I understand that there's weighted coverage of the clusters in the end, but can we directly use that to infer the abundance of the cluster or do we need to use another software to quantify the abundance?

Thank you!

**Comment by WiscEvan** [comment]
Thank you for your question. Currently we do not handle quantifying the abundance of a contig. To directly infer abundance will likely depend on the species and the number of reads representing them. We assign contigs and clusters a _coverage_ as a proxy for abundance, however these values should probably not be used as a direct measure of abundance.

**Comment by proteinosome** [comment]
Okay thank you for your answer!
