### ISSUE TITLE
Use Rsync to download files from NCBI server

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#91]
Rsync uses compression while downloading, and is much faster than regular FTP protocols, so it will save a lot of time using it. The NCBI FTP server supports transfers via rsync, as detailed here:

https://techoverflow.net/2013/12/30/accessing-ncbi-ftp-via-rsync/

**Comment by WiscEvan** [comment]
@jason-c-kwan I believe this can be closed due to merge #77
